
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctosapi.h>
#include <sqlite3.h>

#include "../SOURCE/INCLUDES/Define_1.h"
#include "../SOURCE/INCLUDES/Define_2.h"
#include "../SOURCE/INCLUDES/TransType.h"
#include "../SOURCE/INCLUDES/Transaction.h"
#include "../SOURCE/DISPLAY/Display.h"
#include "../SOURCE/DISPLAY/DispMsg.h"
#include "../SOURCE/DISPLAY/DisTouch.h"
#include "../SOURCE/PRINT/Print.h"
#include "../SOURCE/FUNCTION/Function.h"
#include "../SOURCE/FUNCTION/FuncTable.h"
#include "../SOURCE/FUNCTION/FILE_FUNC/File.h"
#include "../SOURCE/FUNCTION/FILE_FUNC/FIleLogFunc.h"
#include "../SOURCE/FUNCTION/Sqlite.h"
#include "../SOURCE/FUNCTION/Batch.h"
#include "../SOURCE/EVENT/MenuMsg.h"
#include "../SOURCE/EVENT/Flow.h"
#include "../SOURCE/FUNCTION/Accum.h"
#include "../SOURCE/FUNCTION/EDC.h"
#include "../SOURCE/FUNCTION/HDT.h"
#include "../SOURCE/FUNCTION/HDPT.h"
#include "../SOURCE/FUNCTION/CPT.h"
#include "../SOURCE/FUNCTION/CFGT.h"
#include "../SOURCE/FUNCTION/MVT.h"
#include "../SOURCE/FUNCTION/KMS.h"
#include "../SOURCE/FUNCTION/Signpad.h"
#include "../SOURCE/COMM/Comm.h"
#include "../CTLS/CTLS.h"
#include "../EMVSRC/EMVsrc.h"

#include "../SOURCE/FUNCTION/ECR_FUNC/ECR.h"
#include "../SOURCE/KEY/ProcessTmk.h"

#include "../SOURCE/FUNCTION/UNIT_FUNC/TimeUint.h"

#include "FUBONfunc.h"
#include "FUBONiso.h"
#include "FUBONtsam.h"



extern VS_BOOL ECRFlag;
extern int ginDebug; /* Debug使用 extern */
extern EMV_CONFIG EMVGlobConfig;

extern int ginFuUnBlanceSettleFlag;

int SALE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int SALE_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	/* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，
	 * 所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_EMV_PROCESS_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int SALE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	/* DCC不支援DCC+Contactless */
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int VOID_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_FUNCTION_VOID_CHECK_,
	_FUNCTION_VOID_CONFIRM_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REFUND_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REFUND_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	/* DCC不支援DCC+Contactless */
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int SETTLE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_, /*  要再確認是否要在這邊回送 20090124 [SAM]*/
	_FUBON_SET_ONLINE_OFFLINE_,
	_NEXSYS_ESC_UPLOAD_SETTLE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_FUNCTION_PRINT_TOTAL_REPORT_BY_BUFFER_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_, /*  自助結帳回覆 20090124 [SAM]*/
	_FUNCTION_DELETE_BATCH_FLOW_,
	_FUNCTION_DELETE_ACCUM_FLOW_,
	_FUNCTION_REST_BATCH_INV_,
	_FUNCTION_UPDATE_BATCH_NUM_,
	_FUNCTION_DISPLAY_PLEASE_LOGON_FIRST_,
//	_FUNCTION_TMS_SCHEDULE_INQUIRE_,  因為富邦不會這在詢問，所以拿掉 20190213 [SAM]*/
//	_FUNCTION_TMS_DOWNLOAD_SETTLE_,  因為富邦不會這在TMS下載，所以拿掉 20190213 [SAM]*/
	_FUBON_TURN_OFF_SETTLE_FLAG_, /* 設定全域變數為平帳狀態 2020/5/13 上午 10:27 [SAM]*/
	_EDC_BOOTING_CUP_LOGON_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,
};

int TIP_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_TIP_CHECK_,
	_CREDIT_FUNCTION_GET_TIP_AMOUNT_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int ADJUST_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_ADJUST_CHECK_,
	_CREDIT_FUNCTION_GET_ADJUST_AMOUNT_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int SALE_OFFLINE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUBON_FUNCTION_MAKE_REFNO_, /* 富邦 Offline 要自己建立RRn   20190222 [SAM] */
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int SALE_OFFLINE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUBON_FUNCTION_MAKE_REFNO_, /* 富邦 Offline 要自己建立RRn   20190222 [SAM] */
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int PRE_AUTH_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int PRE_AUTH_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int PRE_AUTH_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int PRE_COMP_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_FUNCTION_GET_ORIG_TRANSDATE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int PRE_COMP_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_FUNCTION_GET_ORIG_TRANSDATE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_SALE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_SALE_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_SALE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_REFUND_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_REFUND_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTFEE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_ADJUST_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int INST_ADJUST_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTFEE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_SALE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_SALE_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_SALE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_REFUND_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_REDEEM_PAID_AMT_, /* 新增函式 20190122 [SAM] */
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_REFUND_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_REDEEM_PAID_AMT_, /* 新增函式 20190122 [SAM] */
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_ADJUST_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_REDEEM_PAID_AMT_, /* 新增函式 20190122 [SAM] */
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int REDEEM_ADJUST_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_REDEEM_PAID_AMT_, /* 新增函式 20190122 [SAM] */
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_SALE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_GET_CUP_PIN_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_SALE_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_SALE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_GET_CUP_PIN_,
	_NEXSYS_ESC_CHECK_,
	/* DCC不支援DCC+Contactless */
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	/* DCC不支援DCC+Contactless */
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REFUND_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_FUNCTION_CUP_REFUND_LIMIT_CHECK_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REFUND_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_FUNCTION_CUP_REFUND_LIMIT_CHECK_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_AUTH_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_GET_CUP_PIN_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_AUTH_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_AUTH_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_GET_CUP_PIN_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_COMP_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_COMP_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_ORI_PREAUTH_AMOUNT_,
	_CREDIT_FUNCTION_GET_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_VOID_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_FUNCTION_CUP_VOID_CHECK_,
	_FUNCTION_CUP_VOID_CONFIRM_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_AUTH_VOID_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_FUNCTION_CUP_VOID_CHECK_,
	_FUNCTION_CUP_VOID_CONFIRM_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_PRE_COMP_VOID_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_FUNCTION_CUP_VOID_CHECK_,
	_FUNCTION_CUP_VOID_CONFIRM_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_INST_SALE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_GET_CUP_PIN_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_INST_SALE_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_INST_SALE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_INST_REFUND_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_FUNCTION_CUP_REFUND_LIMIT_CHECK_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTFEE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_INST_REFUND_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_FUNCTION_CUP_REFUND_LIMIT_CHECK_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTFEE_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REDEEM_SALE_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_GET_CUP_PIN_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REDEEM_SALE_ICC_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_EMV_PROCESS_, /* 晶片卡因為在_EMV_PROCESS_才抓卡號，這時才會有對應HOST，所以把_NCCC_FUNCTION_MAKE_REFNO_拉進去(_NCCC_DCC_CHECK_原因相同) */
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REDEEM_SALE_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUNCTION_DUPLICATE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REDEEM_REFUND_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_REDEEM_REFUND_CTLS_TRT_FUBON_TABLE[] ={
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_COMM_MODEM_PREDIAL_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_NEXSYS_ESC_CHECK_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_FUNCTION_UPDATE_INV_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_NEXSYS_ESC_UPLOAD_,
	_FLOW_NULL_,
};

int CUP_LOGON_TABLE[] ={
	_EDC_BOOTING_CUP_LOGON_,
	_FLOW_NULL_,
};



TRT_TABLE TRANSACTION_FUBON_TABLE[] ={
	{_TRT_SALE_, SALE_TRT_FUBON_TABLE},
	{_TRT_SALE_ICC_, SALE_ICC_TRT_FUBON_TABLE},
	{_TRT_SALE_CTLS_, SALE_CTLS_TRT_FUBON_TABLE},
	{_TRT_VOID_, VOID_TRT_FUBON_TABLE},
	{_TRT_REFUND_, REFUND_TRT_FUBON_TABLE},
	{_TRT_REFUND_CTLS_, REFUND_CTLS_TRT_FUBON_TABLE},
	{_TRT_SETTLE_, SETTLE_TRT_FUBON_TABLE},
	{_TRT_TIP_, TIP_TRT_FUBON_TABLE},
	{_TRT_ADJUST_, ADJUST_TRT_FUBON_TABLE},
	{_TRT_SALE_OFFLINE_, SALE_OFFLINE_TRT_FUBON_TABLE},
	{_TRT_SALE_OFFLINE_CTLS_, SALE_OFFLINE_CTLS_TRT_FUBON_TABLE},
	{_TRT_PRE_AUTH_, PRE_AUTH_TRT_FUBON_TABLE},
	{_TRT_PRE_AUTH_ICC_, PRE_AUTH_ICC_TRT_FUBON_TABLE},
	{_TRT_PRE_AUTH_CTLS_, PRE_AUTH_CTLS_TRT_FUBON_TABLE},
	{_TRT_PRE_COMP_, PRE_COMP_TRT_FUBON_TABLE},
	{_TRT_PRE_COMP_CTLS_, PRE_COMP_CTLS_TRT_FUBON_TABLE},
	{_TRT_INST_SALE_, INST_SALE_TRT_FUBON_TABLE},
	{_TRT_INST_SALE_ICC_, INST_SALE_ICC_TRT_FUBON_TABLE},
	{_TRT_INST_SALE_CTLS_, INST_SALE_CTLS_TRT_FUBON_TABLE},
	{_TRT_INST_REFUND_, INST_REFUND_TRT_FUBON_TABLE},
	{_TRT_INST_REFUND_CTLS_, INST_REFUND_CTLS_TRT_FUBON_TABLE},
	{_TRT_INST_ADJUST_, INST_ADJUST_TRT_FUBON_TABLE},
	{_TRT_INST_ADJUST_CTLS_, INST_ADJUST_CTLS_TRT_FUBON_TABLE},
	{_TRT_REDEEM_SALE_, REDEEM_SALE_TRT_FUBON_TABLE},
	{_TRT_REDEEM_SALE_ICC_, REDEEM_SALE_ICC_TRT_FUBON_TABLE},
	{_TRT_REDEEM_SALE_CTLS_, REDEEM_SALE_CTLS_TRT_FUBON_TABLE},
	{_TRT_REDEEM_REFUND_, REDEEM_REFUND_TRT_FUBON_TABLE},
	{_TRT_REDEEM_REFUND_CTLS_, REDEEM_REFUND_CTLS_TRT_FUBON_TABLE},
	{_TRT_REDEEM_ADJUST_, REDEEM_ADJUST_TRT_FUBON_TABLE},
	{_TRT_REDEEM_ADJUST_CTLS_, REDEEM_ADJUST_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_SALE_, CUP_SALE_TRT_FUBON_TABLE},
	{_TRT_CUP_SALE_ICC_, CUP_SALE_ICC_TRT_FUBON_TABLE},
	{_TRT_CUP_SALE_CTLS_, CUP_SALE_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_REFUND_, CUP_REFUND_TRT_FUBON_TABLE},
	{_TRT_CUP_REFUND_CTLS_, CUP_REFUND_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_AUTH_, CUP_PRE_AUTH_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_AUTH_ICC_, CUP_PRE_AUTH_ICC_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_AUTH_CTLS_, CUP_PRE_AUTH_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_COMP_, CUP_PRE_COMP_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_COMP_CTLS_, CUP_PRE_COMP_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_VOID_, CUP_VOID_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_AUTH_VOID_, CUP_PRE_AUTH_VOID_TRT_FUBON_TABLE},
	{_TRT_CUP_PRE_COMP_VOID_, CUP_PRE_COMP_VOID_TRT_FUBON_TABLE},
	{_TRT_CUP_INST_SALE_, CUP_INST_SALE_TRT_FUBON_TABLE},
	{_TRT_CUP_INST_SALE_ICC_, CUP_INST_SALE_ICC_TRT_FUBON_TABLE},
	{_TRT_CUP_INST_SALE_CTLS_, CUP_INST_SALE_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_INST_REFUND_, CUP_INST_REFUND_TRT_FUBON_TABLE},
	{_TRT_CUP_INST_REFUND_CTLS_, CUP_INST_REFUND_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_REDEEM_SALE_, CUP_REDEEM_SALE_TRT_FUBON_TABLE},
	{_TRT_CUP_REDEEM_SALE_ICC_, CUP_REDEEM_SALE_ICC_TRT_FUBON_TABLE},
	{_TRT_CUP_REDEEM_SALE_CTLS_, CUP_REDEEM_SALE_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_REDEEM_REFUND_, CUP_REDEEM_REFUND_TRT_FUBON_TABLE},
	{_TRT_CUP_REDEEM_REFUND_CTLS_, CUP_REDEEM_REFUND_CTLS_TRT_FUBON_TABLE},
	{_TRT_CUP_LOGON_, CUP_LOGON_TABLE},
	{_FLOW_NULL_, NULL}
};

int inFUBON_RunTRT(TRANSACTION_OBJECT *pobTran, int inTRTCode)
{
	int *inTRTID = NULL;
	int i, inRetVal = VS_ERROR;

	for (i = 0;; i++)
	{
		if (TRANSACTION_FUBON_TABLE[i].inTRTCode == inTRTCode)
		{
			inTRTID = TRANSACTION_FUBON_TABLE[i].inTRTID;
			break;
		} else if (TRANSACTION_FUBON_TABLE[i].inTRTCode == -1)
			break;
	}

	if (inTRTID == NULL)
	{
		inECR_SendError(pobTran, VS_USER_OPER_ERR);
		return (VS_ERROR);
	}

	/* 補註解:
	 *  因 inTRTID 結構最後一個元素會設定為 _FLOW_NULL_ 
	 * 所以 inRetVal 的值，會以執行的 inTRTID 功能時最後執行結果為回覆值 2022/9/30 [SAM] */
	for (i = 0;; i++)
	{
		/* 正常的結束TRT流程  */
		if (inTRTID[i] == _FLOW_NULL_)
		{
			break;
		}

		inRetVal = inFLOW_RunFunction(pobTran, inTRTID[i]);

		if (inRetVal != VS_SUCCESS)
		{
			inDISP_LogPrintfWithFlag(" FU Trt inErrorMsg[%d] RetVal[%d]", pobTran->inErrorMsg, inRetVal);
			/* 只有出錯才需SendError */
			if (pobTran->inECRErrorMsg != _ECR_RESPONSE_CODE_NOT_SET_ERROR_)
			{
				inECR_SendError(pobTran, pobTran->inECRErrorMsg);
			} else
			{
				inECR_SendError(pobTran, inRetVal);
			}
			break;
		}

	}

	/* 斷線 */
	inCOMM_End(pobTran);

	/* 要先回傳再顯示錯誤訊息 */
	inFunc_Display_Error(pobTran);

	/* 退回晶片卡 */
	if (inRetVal != VS_SUCCESS)
	{
		inFunc_Check_Card_Still_Exist(pobTran, _REMOVE_CARD_ERROR_);
	} else
	{
		inFunc_Check_Card_Still_Exist(pobTran, _REMOVE_CARD_NOT_ERROR_);
	}

	return (inRetVal);
}

/*
Function		: inFUBON_Func_Must_SETTLE
Date&Time	: 2015/10/22 下午 04:00
Describe		: 確認是否要先結帳
 */
int inFUBON_Func_Must_SETTLE(TRANSACTION_OBJECT *pobTran)
{
	int inSelectHostIndex;
	char szMustSettleBit[2 + 1];
	char szHostName[40 + 1];

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	if (inFunc_Find_Specific_HDTindex(pobTran->srBRec.inHDTIndex, _HOST_NAME_CREDIT_FUBON_, &inSelectHostIndex) != VS_SUCCESS)
	{
		inDISP_DispLogAndWriteFlie(" FU Find Specicifc Hdt *Error* Name[%s]  Line[%d]", _HOST_NAME_CREDIT_FUBON_, __LINE__);
		/* 找不到直接return VS_ERROR */
		return (VS_ERROR);
	}

	inLoadHDPTRec(inSelectHostIndex);
	memset(szMustSettleBit, 0x00, sizeof (szMustSettleBit));

	if (inGetMustSettleBit(szMustSettleBit) == VS_ERROR)
	{
		inDISP_DispLogAndWriteFlie(" FU Get SettleBit *Error* HID[%d]  Line[%d]", inSelectHostIndex, __LINE__);
		return (VS_ERROR);
	}

	/* Load完了要load回原來的HDPT避免意外，如果有的話 */
	inLoadHDPTRec(pobTran->srBRec.inHDTIndex);

	if (!memcmp(szMustSettleBit, "Y", 1))
	{
		/* 表示要結帳 */
		memset(szHostName, 0x00, sizeof (szHostName));
		sprintf(szHostName, "%s", _HOST_NAME_CREDIT_FUBON_);
		inDISP_Msg_BMP(_ERR_MUST_SETTLE_, _COORDINATE_Y_LINE_8_6_, _CLEAR_KEY_MSG_, _EDC_TIMEOUT_, szHostName, _LINE_8_5_);
		inDISP_DispLogAndWriteFlie("-----[%s][%s] Line[%d] MUST SETTLE END -----", __FILE__, __FUNCTION__, __LINE__);

		/* 富邦KIOSK回應設定  2020/2/4 下午 6:54*/
		if (pobTran->uszKioskFlag == 'Y')
			pobTran->inECRErrorMsg = _ECR_RESPONSE_CODE_PLESE_SETTLE_;

		return (VS_ERROR);
	} else
	{
		inDISP_LogPrintfWithFlag("-----[%s][%s] Line[%d] END -----", __FILE__, __FUNCTION__, __LINE__);
		return (VS_SUCCESS);
	}
}

int inFUBON_FuncSetOnlineOffline(TRANSACTION_OBJECT *pobTran)
{
	char szEMVFloorLimit[10 + 1];
	long lnEMVFloorLimit = 0;
	char szTxnType[20 + 1];

	/* offline交易及settle不需要做reversal */
	pobTran->uszReversalBit = VS_TRUE;
	inDISP_LogPrintfWithFlag("-----[%s][%s] Line[%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	/* 用區域的時間計算 */
	unsigned long ulRunTime;
	inTIME_UNIT_InitCalculateRunTimeGlobal_Start(&ulRunTime, "inFUBON_FuncSetOnlineOffline INIT");

	inDISP_DispLogAndWriteFlie(" P-TransCode[%d] Br-OffBit[%d] Br-Upload[%d] Br-Stan[%d] ", pobTran->inTransactionCode, pobTran->srBRec.uszOfflineBit, pobTran->srBRec.uszUpload1Bit, pobTran->srBRec.lnSTANNum);


	if (pobTran->srBRec.uszOfflineBit == VS_TRUE)
		pobTran->uszReversalBit = VS_FALSE;
	else if (pobTran->inTransactionCode == _SETTLE_ || pobTran->inTransactionCode == _CLS_SETTLE_)
		pobTran->uszReversalBit = VS_FALSE;


	if (pobTran->inTransactionCode == _SALE_)
	{
		if (pobTran->srBRec.inChipStatus == _EMV_CARD_/* && pobTran->inEMVTermDecision == FORCE_ONLINE*/)//By Ray
		{
			pobTran->srBRec.uszOfflineBit = VS_FALSE;
			return (VS_SUCCESS);
		}

		if ((!memcmp(pobTran->srBRec.szAuthCode, "VLP", 3) && pobTran->srBRec.uszContactlessBit == VS_TRUE) ||
				(!memcmp(pobTran->srBRec.szAuthCode, "JCB", 3) && pobTran->srBRec.uszContactlessBit == VS_TRUE) ||
				(!memcmp(pobTran->srBRec.szAuthCode, "Y1", 2) && pobTran->srBRec.uszContactlessBit == VS_TRUE) ||
				(!memcmp(pobTran->srBRec.szAuthCode, "Y1", 2) && pobTran->srBRec.inChipStatus == _EMV_CARD_))
		{
			if (pobTran->srBRec.inChipStatus == _EMV_CARD_ && !memcmp(pobTran->srBRec.szAuthCode, "Y1", 2))
			{

				if (!memcmp(pobTran->srBRec.szCardLabel, _CARD_TYPE_VISA_, strlen(_CARD_TYPE_VISA_)))
					inLoadMVTRec(_VISA_MVT_INDEX_); /* VISA */
				else if (!memcmp(pobTran->srBRec.szCardLabel, "MASTER CARD", strlen("MASTER CARD")))
					inLoadMVTRec(_MCHIP_MVT_INDEX_); /* MASTER CARD */
				else if (!memcmp(pobTran->srBRec.szCardLabel, _CARD_TYPE_JCB_, strlen(_CARD_TYPE_JCB_)))
					inLoadMVTRec(_JSMART_MVT_INDEX_); /* J SMART */
				else
				{
					inDISP_DispLogAndWriteFlie(" FU SetOnlineOffelin *Error* Label[%s] Line[%d] ", pobTran->srBRec.szCardLabel, __LINE__);
					inDISP_Msg_BMP(_ERR_EMV_FLOW_, _COORDINATE_Y_LINE_8_5_, _CLEAR_KEY_MSG_, _EDC_TIMEOUT_, "", 0);
					return (VS_ERROR);
				}

				memset(szEMVFloorLimit, 0x00, sizeof (szEMVFloorLimit));

				inGetEMVFloorLimit(szEMVFloorLimit);
				lnEMVFloorLimit = atol(szEMVFloorLimit);

				if (pobTran->srBRec.lnTxnAmount >= lnEMVFloorLimit)
				{
					inDISP_DispLogAndWriteFlie(" FU SetOnlineOffelin OverLimit *Error* EMVFloorLimit[%ld] lnTxnAmount[%ld] Line[%d] ", lnEMVFloorLimit, pobTran->srBRec.lnTxnAmount, __LINE__);
					inDISP_Msg_BMP(_ERR_EMV_FLOW_, _COORDINATE_Y_LINE_8_5_, _CLEAR_KEY_MSG_, _EDC_TIMEOUT_, "", 0);
					return (VS_ERROR);
				}
			}

			pobTran->srBRec.uszOfflineBit = VS_TRUE;

			if (pobTran->srBRec.uszUpload1Bit == VS_FALSE)
			{
				pobTran->srBRec.uszUpload1Bit = VS_TRUE;
				pobTran->srBRec.uszUpload2Bit = VS_FALSE;
			} else if (pobTran->srBRec.uszUpload2Bit == VS_FALSE)
				pobTran->srBRec.uszUpload2Bit = VS_TRUE;
			else
			{
				inDISP_DispLogAndWriteFlie(" FU SetOnlineOffelin UpBit *Error* uszUpload1Bit[%ld] uszUpload2Bit[%ld] Line[%d] ", pobTran->srBRec.uszUpload1Bit, pobTran->srBRec.uszUpload2Bit, __LINE__);
				return (VS_ERROR);
			}
		}
	} else if (pobTran->inTransactionCode == _SALE_OFFLINE_)
	{
		memset(szTxnType, 0x00, sizeof (szTxnType));
		inGetTransFunc(szTxnType);

		pobTran->srBRec.uszOfflineBit = VS_TRUE;
		pobTran->srBRec.uszUpload1Bit = VS_TRUE;
		pobTran->srBRec.uszUpload2Bit = VS_FALSE;

	} else if (pobTran->inTransactionCode == _VOID_)
	{
		if (pobTran->srBRec.uszOfflineBit == VS_TRUE && pobTran->srBRec.uszUpload1Bit == VS_TRUE)
		{
			pobTran->srBRec.uszOfflineBit = VS_TRUE;
			pobTran->srBRec.uszUpload1Bit = VS_TRUE;
			pobTran->srBRec.uszUpload2Bit = VS_TRUE;
			pobTran->srBRec.lnSTAN_Multi = pobTran->srBRec.lnSTANNum;
		} else if (pobTran->srBRec.uszOfflineBit == VS_TRUE && pobTran->srBRec.uszUpload1Bit == VS_FALSE)
		{
			pobTran->srBRec.uszOfflineBit = VS_FALSE;
			pobTran->srBRec.uszUpload1Bit = VS_FALSE;
			pobTran->srBRec.uszUpload2Bit = VS_FALSE;
		} else
			pobTran->srBRec.uszOfflineBit = VS_FALSE;
	} else if (pobTran->inTransactionCode == _TIP_ || pobTran->inTransactionCode == _ADJUST_)
	{
		if (pobTran->srBRec.uszOfflineBit == VS_TRUE && pobTran->srBRec.uszUpload1Bit == VS_TRUE)
		{
			pobTran->srBRec.uszOfflineBit = VS_TRUE;
			pobTran->srBRec.uszUpload1Bit = VS_TRUE;
			pobTran->srBRec.uszUpload2Bit = VS_TRUE;
			pobTran->srBRec.lnSTAN_Multi = pobTran->srBRec.lnSTANNum;
		} else if (pobTran->srBRec.uszOfflineBit == VS_TRUE && pobTran->srBRec.uszUpload1Bit == VS_FALSE)
		{

			pobTran->srBRec.uszOfflineBit = VS_FALSE;
			pobTran->srBRec.uszUpload1Bit = VS_FALSE;
			pobTran->srBRec.uszUpload2Bit = VS_FALSE;
			pobTran->uszReversalBit = VS_TRUE;
		} else
		{
			pobTran->srBRec.uszOfflineBit = VS_FALSE;
			pobTran->uszReversalBit = VS_TRUE;
		}
	} else
	{
		pobTran->srBRec.uszOfflineBit = VS_FALSE;
		pobTran->srBRec.uszUpload1Bit = VS_FALSE;
		pobTran->srBRec.uszUpload2Bit = VS_FALSE;
	}

	inDISP_DispLogAndWriteFlie(" FU TranCode[%d] uszReversalBit[%d] lnSTAN_Multi[%ld] STANNum[%ld]", pobTran->inTransactionCode, pobTran->uszReversalBit, pobTran->srBRec.lnSTAN_Multi, pobTran->srBRec.lnSTANNum);
	inDISP_DispLogAndWriteFlie(" FU OfflineBit[%d] Upload1Bit[%d] Upload2Bit[%d] ", pobTran->srBRec.uszOfflineBit, pobTran->srBRec.uszUpload1Bit, pobTran->srBRec.uszUpload2Bit);
	inTIME_UNIT_GetRunTimeGlobal(ulRunTime, " inFUBON_FuncSetOnlineOffline END");
	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] END -----", __FILE__, __FUNCTION__, __LINE__);
	return (VS_SUCCESS);
}

/*
Function		:inFUBON_OnlineEMV_Complete
Date&Time	:2016/11/17 下午 4:55
Describe		:處理Second Gen AC之後TC or Reversal
 */
int inFUBON_OnlineEMV_Complete(TRANSACTION_OBJECT *pobTran)
{
	int inRetVal;
	unsigned char uszValue[128 + 1];
	unsigned short usTagLen;
	RTC_NEXSYS srRTC;

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	/* 新增感應及晶片go online防呆機制，若卡片進入offline流程，畫面提示”OL 拒絕交易”。*/
	if (pobTran->inEMVDecision == _EMV_DECESION_OFFLINE)
	{
		memcpy(pobTran->srBRec.szRespCode, "OL", strlen("OL"));
		inFUBON_DispHostResponseCode(pobTran);
		inDISP_DispLogAndWriteFlie(" FU EmvComplete EMVDesision *Error* Line[%d]", __LINE__);
		return (VS_ERROR);
	}

	/* 8A */
	usTagLen = sizeof (uszValue);
	memset(uszValue, 0x00, sizeof (uszValue));
	inEMV_Get_Tag_Value(0x8A, &usTagLen, uszValue);

	inDISP_LogPrintfWithFlag("  Fubon EmvComplete Get 8A[%s]", uszValue);

	/*  先檢核first gen AC的結果 若是Y1 或 Z1就不用在做Second Gen AC */
	if (!memcmp(uszValue, "Z1", 2))
	{
		/* Z1= declined offline (first Gen AC , CID=AAC) */
		/* 拒絕交易 */
		inDISP_DispLogAndWriteFlie(" FU EmvComplete  First Gen AC Z1 *Error* Line[%d]", __LINE__);

		memset(pobTran->srBRec.szRespCode, 0x00, sizeof (pobTran->srBRec.szRespCode));
		memset(pobTran->srBRec.szAuthCode, 0x00, sizeof (pobTran->srBRec.szAuthCode));
		strcpy(pobTran->srBRec.szRespCode, "Z1");
		strcpy(pobTran->srBRec.szAuthCode, "Z1");

		inFUBON_DispHostResponseCode(pobTran);

		return (VS_ERROR);
	} else if (!memcmp(uszValue, "Y1", 2))
	{
		/* EMV First Gen AC產生Y1 */
		inDISP_DispLogAndWriteFlie(" FU EmvComplete  First Gen AC Y1 *Error* Line[%d]", __LINE__);

		memset(pobTran->srBRec.szRespCode, 0x00, sizeof (pobTran->srBRec.szRespCode));
		memset(pobTran->srBRec.szAuthCode, 0x00, sizeof (pobTran->srBRec.szAuthCode));
		strcpy(pobTran->srBRec.szRespCode, "Y1");
		strcpy(pobTran->srBRec.szAuthCode, "Y1");

		/* 因為Y1不需要簽名 */
		pobTran->srBRec.uszF56NoSignatureBit = VS_TRUE;
		/* 卡片自行授權時（授權碼為 Y1/Y3），端末設備以 Offline Sale 電文上傳，
		 * 但 EMV Tag 資料視為 TC Upload。*/
		/* 將EMV參數更新存檔 */
		if (inNCCC_FuncEMVPrepareBatch(pobTran) != VS_SUCCESS)
		{
			inDISP_DispLogAndWriteFlie(" FU EmvComplete EmvPreapreBatch *Error* Line[%d]", __LINE__);
			inFunc_EDCLock();
			return (VS_ERROR);
		}

		/* 這裡是晶片卡offline 要疊加STAN */
		inFUBON_GetSTAN(pobTran);
		inFUBON_SetSTAN(pobTran);

		/* Y1存 Advice */
		if (inADVICE_SaveTop(pobTran, pobTran->srBRec.lnOrgInvNum) != VS_SUCCESS)
		{
			inDISP_DispLogAndWriteFlie(" FU EmvComplete ADV Save Top *Error* Line[%d]", __LINE__);
			return (VS_ERROR);
		} else
		{
			inDISP_LogPrintfWithFlag(" Fubon EmvComplete  ADV Save Top  SUCCESS!");
		}

		return (VS_SUCCESS);
	} else
	{
		inDISP_LogPrintfWithFlag("  Fubon EmvComplet TranCode[%d] TransResult[%d]", pobTran->inTransactionCode, pobTran->inTransactionResult);
		/* 要處理Second Gen AC之後的流程，含TC Upload（Call Bank的狀況） */
		if (pobTran->inTransactionResult == _TRAN_RESULT_REFERRAL_ && (pobTran->inTransactionCode == _SALE_ || pobTran->inTransactionCode == _CUP_SALE_))
		{
			inDISP_DispLogAndWriteFlie(" FU Do Referral Flow TranCode[%d] TransResult[%d] Line[%d]", pobTran->inTransactionCode, pobTran->inTransactionResult, __LINE__);
			/* 交易補登Online 當筆就執行Call Bank(不必送TC Upload) */
			pobTran->inTransactionResult = _TRAN_RESULT_AUTHORIZED_;
			pobTran->srBRec.uszReferralBit = VS_TRUE;
			pobTran->srBRec.uszForceOnlineBit = VS_TRUE;
			pobTran->srBRec.uszOfflineBit = VS_FALSE;
			pobTran->srBRec.uszUpload1Bit = VS_FALSE;
			pobTran->srBRec.uszUpload2Bit = VS_FALSE;
			pobTran->srBRec.uszUpload3Bit = VS_FALSE;

			/* 取得EDC時間日期 */
			memset(&srRTC, 0x00, sizeof (RTC_NEXSYS));
			if (inFunc_GetSystemDateAndTime(&srRTC) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU EmvComplet Get Time *Error* Line[%d] ", __LINE__);
				return (VS_ERROR);
			}

			/* 更新pobTran內日期時間 */
			if (inFunc_Sync_BRec_Date_Time(pobTran, &srRTC) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU EmvComplet Sync Time *Error* Line[%d] ", __LINE__);
				return (VS_ERROR);
			}

			/* Second Generate AC失敗但是銀行授權成功還是要算成功，
			 * 因Second Gen AC在OnTxnResult前由API自己改晶片卡資料，
			 * 而且call bank 以補登送要送原AuthCode，所以不再call inEMV_SecondGenerateAC來改pobTran的資料 */

			/*
			2014-08-14
			From: 吳升文(Angus Wu) [mailto:angus.wu@nccc.com.tw]
			Sent: Tuesday, August 12, 2014 9:01 PM

			若為CallBank完成之晶片卡交易，端末機需上傳Field_55，其Tag 8A之值須為”0x30 0x30”。
			補充說明：晶片卡Callbank時，卡片需要插在EDC中直到輸入授權碼後，執行EMV 2nd AC(Request TC)。
			故該筆Callbank交易完成交易需上傳Field_55。
			 */
			if (inEMV_Set_TagValue_During_Txn(d_TAG_ARC, 2, (unsigned char*) "\x30\x30") != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU Set TAG_ARC *Error* Line[%d] ", __LINE__);
				return (VS_ERROR);
			}

			/* 將EMV參數更新存檔 */
			if (inNCCC_FuncEMVPrepareBatch(pobTran) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU EmvComplete EmvPreapreBatch *Error* Line[%d] ", __LINE__);
				inFunc_EDCLock();
				return (VS_ERROR);
			}

			if (inADVICE_SaveAppend(pobTran, pobTran->srBRec.lnOrgInvNum) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU EmvComplete ADV Save Append OrgInv[%d] *Error* Line[%d]", pobTran->srBRec.lnOrgInvNum, __LINE__);
				return (VS_ERROR);
			}

			inDISP_ClearAll();
			inFunc_Display_LOGO(0, _COORDINATE_Y_LINE_16_2_); /* 第一層顯示 LOGO */
			inDISP_PutGraphic(_MENU_SALE_OFFLINE_TITLE_, 0, _COORDINATE_Y_LINE_8_3_); /* 第三層顯示 交易補登 */

			pobTran->srBRec.inCode = _SALE_OFFLINE_; /* 交易補登 */
			pobTran->inTransactionCode = _SALE_OFFLINE_; /* 交易補登 */
			pobTran->inISOTxnCode = _SALE_OFFLINE_;

			/* 避免撥接太久，收送完就斷線 */
			inCOMM_End(pobTran);

			return (VS_SUCCESS);
		} else if (pobTran->inTransactionCode == _PRE_AUTH_ || pobTran->inTransactionCode == _CUP_PRE_AUTH_)
		{
			/* 開始執行 Second Generate AC */
			inRetVal = inEMV_SecondGenerateAC(pobTran);

			inDISP_DispLogAndWriteFlie(" FU EmvComplete AUTH SecGenAc TR[%d] AC[%d] RV[%d] Line[%d]", pobTran->inTransactionResult, inRetVal, pobTran->srBRec.szAuthCode, __LINE__);

			/* 將EMV參數更新存檔 */
			if (inNCCC_FuncEMVPrepareBatch(pobTran) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU EmvComplete EMVPrepareBatch *Error* Line[%d]", __LINE__);
				inFunc_EDCLock();
				return (VS_ERROR);
			}

			if (inRetVal == VS_SUCCESS)
			{
				/* 這裡成功交易有2種【通訊成功】【通訊失敗產生Y3】 */
				/* Pre Auth 通訊成功後，不用送TC */
				if (memcmp(&pobTran->srBRec.szAuthCode[0], "Y3", 2) != 0)
				{
					/* ISR REVERSAL  */
					if (inFUBON_ISO_ISR_ReversalSave(pobTran) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE *Error* Line[%d]", __LINE__);
						return (VS_ERROR);
					}

					inSetSendReversalBit("N");
					if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete saveHDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
						inFunc_EDCLock();
						return (VS_ERROR);
					}

					return (VS_SUCCESS);
				}					/* Pre Auth 沒有Y3 */
				else
				{
					memset(pobTran->srBRec.szRespCode, 0x00, sizeof (pobTran->srBRec.szRespCode));
					strcpy(pobTran->srBRec.szRespCode, "05");
					inFUBON_DispHostResponseCode(pobTran);

					if (inFUBON_ISO_ISR_ReversalSave(pobTran) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE *Error* Line[%d]", __LINE__);
						return (VS_ERROR);
					}

					return (VS_ERROR);
				}

			}				/* Second Gen AC Fail */
			else
			{
				/* 因為主機回成功或是通訊失敗但是最後卡片拒絕交易所以要組重新組【REVERSAL】 */
				if (pobTran->inTransactionResult == _TRAN_RESULT_AUTHORIZED_ || pobTran->inTransactionResult == _TRAN_RESULT_COMM_ERROR_)
				{
					/* 重組【REVERSAL】 */
					if (inFUBON_ISO_ReversalSave_Flow(pobTran, _REVERSAL_) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE_FLOW *Error* Line[%d]", __LINE__);
						inFunc_EDCLock();
						return (VS_ERROR);
					}

					if (inFUBON_ISO_ISR_ReversalSave(pobTran) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE *Error* Line[%d]", __LINE__);
						return (VS_ERROR);
					}

					if (pobTran->srEMVRec.in71_IssuerScript1Len > 0 || pobTran->srEMVRec.in72_IssuerScript2Len > 0)
					{
						inDISP_LogPrintfWithFlag("  ISR Sript Set 0 Line[%d]", __LINE__);
						inSetMustISRUploadEnableBit("0");
						if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) < 0)
						{
							inDISP_DispLogAndWriteFlie(" FU EmvComplete saveHDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
							return (VS_ERROR);
						}
					}

					/* 拒絕交易Z3 */
					inFUBON_DispHostResponseCode(pobTran);
				} else
				{
					/* ISR REVERSAL */
					if (inFUBON_ISO_ISR_ReversalSave(pobTran) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE *Error* Line[%d]", __LINE__);
						return (VS_ERROR);
					}

					inSetSendReversalBit("N");
					if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete saveHDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
						inFunc_EDCLock();
						return (VS_ERROR);
					}

					/* 拒絕交易 */
					inFUBON_DispHostResponseCode(pobTran);
				}

				return (VS_ERROR);
			}
		} else
		{
			/* 開始執行 Second Generate AC */
			inRetVal = inEMV_SecondGenerateAC(pobTran);

			inDISP_DispLogAndWriteFlie(" FU EmvComplete Normal SecGenAC TR[%d] AC[%d] RV[%d] Line[%d]", pobTran->inTransactionResult, inRetVal, pobTran->srBRec.szAuthCode, __LINE__);

			/* 將EMV參數更新存檔 */
			if (inNCCC_FuncEMVPrepareBatch(pobTran) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU EmvComplete EMVPrepareBatch *Error* Line[%d]", __LINE__);
				inFunc_EDCLock();
				return (VS_ERROR);
			}

			if (pobTran->srBRec.uszCUPTransBit == VS_TRUE)
			{
				inDISP_LogPrintfWithFlag(" CUP ISR REVERSAL REFORM Line[%d]", __LINE__);

				/* ISR REVERSAL */
				if (inFUBON_ISO_ISR_ReversalSave(pobTran) != VS_SUCCESS)
				{
					inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE *Error* Line[%d]", __LINE__);
					return (VS_ERROR);
				}
			}
			/*
			若是預借現金通訊失敗直接Return
			端末機還是要執行Second Gen AC，不過請端末機判斷若是因Unable to go Online產生Y3 (TC)，端末機請直接轉為通訊錯誤(或失敗)之訊息
			 */
			if (pobTran->inTransactionCode == _CASH_ADVANCE_ && pobTran->inTransactionResult == _TRAN_RESULT_COMM_ERROR_)
			{
				inRetVal = VS_ERROR;
			}

			/* Second Gen AC Approve */
			if (inRetVal == VS_SUCCESS)
			{
				if (pobTran->inTransactionResult == _TRAN_RESULT_AUTHORIZED_)
				{
					/* 這裡成功交易有2種【通訊成功】【通訊失敗產生Y3】 */
					if (memcmp(&pobTran->srBRec.szAuthCode[0], "Y3", 2) != 0)
					{
						inSetSendReversalBit("N");
						if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) != VS_SUCCESS)
						{
							inDISP_DispLogAndWriteFlie(" FU EmvComplete saveHDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
							inFunc_EDCLock();
							return (VS_ERROR);
						}

					}/* Y3 */
					else
					{
						/* 防呆紅利分期不會有【Y3】 */
						if (pobTran->inTransactionCode == _INST_SALE_ ||
							pobTran->inTransactionCode == _REDEEM_SALE_ ||
							pobTran->inTransactionCode == _CUP_SALE_)
						{
							memset(pobTran->srBRec.szRespCode, 0x00, sizeof (pobTran->srBRec.szRespCode));
							strcpy(pobTran->srBRec.szRespCode, "05");
							inFUBON_DispHostResponseCode(pobTran);
							inDISP_DispLogAndWriteFlie(" FU EmvComplete INST Or REDEEM Y3 *Error* Line[%d]", __LINE__);
							return (VS_ERROR);
						}

					}

					inDISP_LogPrintfWithFlag(" FU EmvComplete Normal SecGenAC SUCCESS Line[%d]", __LINE__);

					/* 在這裡送【TC UPLOAD】或組【Y3 Advice】 */
					pobTran->uszTCUploadBit = VS_TRUE;
					pobTran->srBRec.uszTCUploadBit = VS_FALSE;
					/* TC_UPLOAD 要加一，要先把0200的STAN抓出來 */
					inFUBON_GetSTAN(pobTran);

					inDISP_LogPrintfWithFlag(" FU EmvComplete TC STAN[%d] Bef COM_START Line[%d]", pobTran->srBRec.lnSTANNum, __LINE__);
					/* Add by hanlin 2013/9/10 PM 03:38:48 因為EMV流程會在inMCAP_ISO_BuildAndSendPacket完之後再跑OnlineAnalyse，因此要重新連一次 */
					inRetVal = inFLOW_RunFunction(pobTran, _COMM_START_);

					inDISP_LogPrintfWithFlag(" FU EmvComplete TC STAN[%d] Aft COM_START Line[%d]", pobTran->srBRec.lnSTANNum, __LINE__);

					inFUBON_SetSTAN(pobTran);

					if (inRetVal != VS_SUCCESS)
					{
						/* 失敗要存 Advice */
						if (inADVICE_SaveTop(pobTran, pobTran->srBRec.lnOrgInvNum) != VS_SUCCESS)
						{
							inDISP_DispLogAndWriteFlie(" FU EmvComplete ADV Save TOP OrgInv[%d] *Error* Line[%d]", pobTran->srBRec.lnOrgInvNum, __LINE__);
							inFunc_EDCLock();
							return (VS_ERROR);
						}

						return (VS_SUCCESS);
					}						/* 連線成功*/
					else
					{
						/* 送TC UPLOAD或advice*/
						inDISP_LogPrintfWithFlag(" FU EmvComplete Send TC Or Advice Line[%d]", __LINE__);
						inRetVal = inFUBON_ISO_SendAdvice(pobTran, 1, VS_TRUE);

						if (inRetVal != VS_SUCCESS)
						{
							inDISP_DispLogAndWriteFlie(" FU EmvComplete Send TC Or Advice *Error* Rvl[%d] Line[%d]", inRetVal, __LINE__);

							/* 失敗要存 Advice */
							if (inADVICE_SaveTop(pobTran, pobTran->srBRec.lnOrgInvNum) != VS_SUCCESS)
							{
								inDISP_DispLogAndWriteFlie(" FU EmvComplete ADV Save TOP OrgInv[%d] *Error* Line[%d]", pobTran->srBRec.lnOrgInvNum, __LINE__);
								inFunc_EDCLock();
								return (VS_ERROR);
							}

							return (VS_SUCCESS);
						} else
						{
							inDISP_LogPrintfWithFlag(" FU EmvComplete Send TC Or Advice SUCCESS Line[%d]", __LINE__);

							/* 這裡是For當筆，因為inNCCC_ATS_ISOAdviceAnalyse的pobTran是ADVPobTran，
								所以TRT的update Batch不會存到在那裡的改動 */
							/* 在這裡把bit On起來，避免TC重送 */
							pobTran->srBRec.uszTCUploadBit = VS_TRUE;

							return (VS_SUCCESS);
						}

					}

				}/* 主機拒絕，不用多做處理 */
				else
				{
					inDISP_DispLogAndWriteFlie(" FU EmvComplete Host Reject[%d] Line[%d]", pobTran->inTransactionResult, __LINE__);
					return (VS_ERROR);
				}

			} else
			{
				/* 因為主機回成功或是通訊失敗但是最後卡片拒絕交易所以要組重新組【REVERSAL】 */
				if (pobTran->inTransactionResult == _TRAN_RESULT_AUTHORIZED_ || pobTran->inTransactionResult == _TRAN_RESULT_COMM_ERROR_)
				{
					/* 重組【REVERSAL】 */
					if (inFUBON_ISO_ReversalSave_Flow(pobTran, _REVERSAL_) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE_FLOW *Error* Line[%d]", __LINE__);
						inFunc_EDCLock();
						return (VS_ERROR);
					}

					if (inFUBON_ISO_ISR_ReversalSave(pobTran) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete ISR_REV_SAVE *Error* Line[%d]", __LINE__);
						return (VS_ERROR);
					}

					/* 拒絕交易Z3 */
					if (pobTran->inTransactionCode == _CASH_ADVANCE_ && pobTran->inTransactionResult == _TRAN_RESULT_COMM_ERROR_)
					{

					} else
						inFUBON_DispHostResponseCode(pobTran); /* 拒絕交易Z3 */
				} else
				{
					inSetSendReversalBit("N");
					if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) != VS_SUCCESS)
					{
						inDISP_DispLogAndWriteFlie(" FU EmvComplete saveHDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
						inFunc_EDCLock();
						return (VS_ERROR);
					}

					inFUBON_DispHostResponseCode(pobTran); /* 拒絕交易 */
				}

				return (VS_ERROR);
			}

		}

	}
}

/*
App Name      :	inFUBON_OnlineAnalyseMagneticManual
App Builder     :	
App Date&Time :
App Function  : 
Input Param   :
Output Param  : 
 */
int inFUBON_OnlineAnalyseMagneticManual(TRANSACTION_OBJECT *pobTran)
{
	int inRetVal = VS_SUCCESS;
	RTC_NEXSYS srRTC; /* Date & Time */

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	inDISP_LogPrintfWithFlag(" P-TxnResult[%d] B.inHDTIndex[%d] ", pobTran->inTransactionResult, pobTran->srBRec.inHDTIndex);

	if (pobTran->inTransactionCode == _SETTLE_)
	{
		if (memcmp(pobTran->srBRec.szRespCode, "95", 2) && memcmp(pobTran->srBRec.szRespCode, "00", 2))
			inRetVal = VS_ERROR;
		else
		{
			if (pobTran->inTransactionResult == _TRAN_RESULT_SETTLE_UPLOAD_BATCH_ && !memcmp(pobTran->srBRec.szRespCode, "95", 2))
			{
				inRetVal = inFUBON_ISO_ProcessSettleBatchUpload(pobTran);
			}
		}
	} else
	{
		if (pobTran->inTransactionResult == _TRAN_RESULT_AUTHORIZED_)
		{
			if (inFUBON_SyncHostTerminalDateTime(pobTran) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse MSG Auth Sucess Sync Time *Error* Line[%d]", __LINE__);
				return (VS_ERROR);
			}

			if (pobTran->srBRec.uszOfflineBit == VS_FALSE)
			{
				inSetSendReversalBit("N");
				if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) == VS_ERROR)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse MSG Auth Sucess HDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
					return (VS_ERROR);
				}

				if (pobTran->inTransactionCode != _CHANGE_TMK_ && pobTran->inTransactionCode != _CUP_CHANG_TPK_)
					inFUBON_ISO_SendAdvice(pobTran, 1, VS_FALSE);
			}
		} else if ((pobTran->inTransactionResult == _TRAN_RESULT_REFERRAL_) &&
				(pobTran->inTransactionCode == _SALE_ || pobTran->inTransactionCode == _CUP_SALE_))
		{
			if (pobTran->srBRec.uszOfflineBit == VS_FALSE)
			{
				inSetSendReversalBit("N");
				if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) == VS_ERROR)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse MSG Referral HDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
					return (VS_ERROR);
				}
			}

			if (inFUBON_SyncHostTerminalDateTime(pobTran) != VS_SUCCESS)
			{
				inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse MSG Referral Sync Time *Error* Line[%d]", __LINE__);
				return (VS_ERROR);
			}

			if ((inRetVal = inFUBON_ISO_REFERRAL_GetManualApproval(pobTran)) == VS_SUCCESS)
			{
				pobTran->inTransactionResult = _TRAN_RESULT_AUTHORIZED_;
				pobTran->uszReferralBit = VS_TRUE;
				pobTran->srBRec.uszReferralBit = VS_TRUE;
				pobTran->srBRec.uszOfflineBit = VS_TRUE;
				pobTran->srBRec.uszUpload1Bit = VS_TRUE;
				pobTran->srBRec.uszUpload2Bit = VS_FALSE;


				memset(&srRTC, 0x00, sizeof (RTC_NEXSYS));
				if (inFunc_GetSystemDateAndTime(&srRTC) != VS_SUCCESS)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse Get System Date Time *Error* Line[%d]", __LINE__);
				}

				if (inFunc_Sync_BRec_Date_Time(pobTran, &srRTC) != VS_SUCCESS)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse Sync BRec Date Time *Error* Line[%d]", __LINE__);
				}

				/* Store Advice */
				if (inADVICE_SaveAppend(pobTran, pobTran->srBRec.lnOrgInvNum) != VS_SUCCESS)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse Msg ADV SaveAddend OrgInv[%d] *Error* Line[%d]", pobTran->srBRec.lnOrgInvNum, __LINE__);
					inRetVal = VS_ERROR;
				}

				inDISP_ClearAll();
				inFunc_Display_LOGO(0, _COORDINATE_Y_LINE_16_2_);
				inDISP_PutGraphic(_MENU_CALL_BANK_TITLE_, 0, _COORDINATE_Y_LINE_8_3_);
				pobTran->srBRec.inCode = _SALE_OFFLINE_;
				pobTran->inTransactionCode = _SALE_OFFLINE_;
			} else
			{
				inRetVal = VS_ERROR;
				inDISP_ClearAll();
			}


		} else if (pobTran->inTransactionResult == _TRAN_RESULT_CANCELLED_)
		{
			if (pobTran->srBRec.uszOfflineBit == VS_FALSE)
			{
				inSetSendReversalBit("N");
				if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) == VS_ERROR)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse MSG Cancel HDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
					return (VS_ERROR);
				}
			}

			inFUBON_DispHostResponseCode(pobTran);
			inRetVal = VS_ERROR;
		} else
		{
			memset(pobTran->srBRec.szRespCode, 0x00, sizeof (pobTran->srBRec.szRespCode));
			inFUBON_DispHostResponseCode(pobTran);
			inRetVal = VS_ERROR;
		}
	}

	inDISP_LogPrintfWithFlag("  inRetVal[%d]", inRetVal);
	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);
	return (inRetVal);
}

/*
Function        : inFUBON_OnlineAnalyseEMV
Date&Time       :2016/11/17 下午 4:57
Describe        :分析結果
 */
int inFUBON_OnlineAnalyseEMV(TRANSACTION_OBJECT *pobTran)
{
	int inRetVal = VS_SUCCESS;

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	/* 初始化主機回傳結果 */
	EMVGlobConfig.uszAction = 0;

	/* 用區域的時間計算 */
	unsigned long ulRunTime;
	inTIME_UNIT_InitCalculateRunTimeGlobal_Start(&ulRunTime, "inFUBON_OnlineAnalyseEMV INIT");
	inDISP_LogPrintfWithFlag("  P-inTransactionResult[%d] P-inTransactionCode[%d]", pobTran->inTransactionResult, pobTran->inTransactionCode);

	/* 若通訊失敗則要產生Y3，須在這裡填入bAction回傳給Kernal */
	/*
	Mail 2013/09/27 RE: V5S開發EMV流程相關問題
	5.在OnTxnOnline流程中，若是晶片通訊失敗我要如何回傳給Kernal產生Y3?(因沒有Response Code無法給pAuthorizationCode)
	Ans: 若要Y3，則在EMV_ONLINE_RESPONSE_DATA結構中的bAction 變數，填上 d_ONLINE_ACTION_UNABLE (03h)。
	 */
	if (pobTran->inTransactionResult == _TRAN_RESULT_COMM_ERROR_ && (pobTran->inTransactionCode == _SALE_ || pobTran->inTransactionCode == _CUP_SALE_))
	{
		if (pobTran->srBRec.uszOfflineBit == VS_FALSE)
		{
			inSetSendReversalBit("N");
			inSaveHDPTRec(pobTran->srBRec.inHDTIndex);
		}
		/* 將主機下來的回覆資料依照Kernel的要求塞入指定的參數中 */
		EMVGlobConfig.uszAction = d_ONLINE_ACTION_UNABLE;
		/* 主機Response Code */
		memcpy(pobTran->srBRec.szRespCode, "Y3", 2);
	} else if (pobTran->inTransactionResult == _TRAN_RESULT_REFERRAL_ && (pobTran->inTransactionCode == _SALE_ || pobTran->inTransactionCode == _CUP_SALE_))
	{
/* 要更新端末機的日期及時間 */
//		if (inFunc_SetEDCDateTime(pobTran->srBRec.szDate, pobTran->srBRec.szTime) != VS_SUCCESS)
//			return (VS_ERROR);

		/* 開始執行【Call Bank】流程 */
		if ((inRetVal = inFunc_REFERRAL_GetManualApproval(pobTran)) == VS_SUCCESS)
		{
			/* 主機回傳結果 */
			EMVGlobConfig.uszAction = d_ONLINE_ACTION_ISSUER_REFERRAL_APPR;
			pobTran->inECRErrorMsg = VS_CALLBANK; /* 修改ECR 回傳CALL BANK 問題 20190215 [SAM] */
			inSetSendReversalBit("N");
			inSaveHDPTRec(pobTran->srBRec.inHDTIndex);
		}			/* Call Bank 失敗，拿不到授權碼 */
		else
		{
			/* 主機回傳結果 */
			EMVGlobConfig.uszAction = d_ONLINE_ACTION_ISSUER_REFERRAL_DENY;
			pobTran->inTransactionResult = _TRAN_RESULT_DECLINED_;

			inSetSendReversalBit("N");
			inSaveHDPTRec(pobTran->srBRec.inHDTIndex);
		}

		/* Second Gen AC會在Online後執行，執行完Second Gen AC的流程在OnTxnResult中執行 */
	} else if (pobTran->inTransactionCode == _PRE_AUTH_ || pobTran->inTransactionCode == _CUP_PRE_AUTH_)
	{
		/* 2011-05-27 AM 09:58:33 修正晶片做預先授權會送TC-upload */
		if (pobTran->inTransactionResult == _TRAN_RESULT_AUTHORIZED_)
		{
			/* 主機回傳結果 */
			EMVGlobConfig.uszAction = d_ONLINE_ACTION_APPROVAL;

			/* 要更新端末機的日期及時間 */
//			if (inFunc_SetEDCDateTime(pobTran->srBRec.szDate, pobTran->srBRec.szTime) != VS_SUCCESS)
//				 return (VS_ERROR);

			inSetSendReversalBit("N");
			inSaveHDPTRec(pobTran->srBRec.inHDTIndex);

		}			/* 主機拒絕交易 */
		else
		{
			/* 主機回傳結果 */
			EMVGlobConfig.uszAction = d_ONLINE_ACTION_DECLINE;

			if (pobTran->inTransactionResult == _TRAN_RESULT_CANCELLED_)
			{
				inSetSendReversalBit("N");
				if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) == VS_ERROR)
				{
					inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse EMV Cancel HDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
					return (VS_ERROR);
				}

				inFUBON_DispHostResponseCode(pobTran); /* 顯示主機回的錯誤訊息 */
				inDISP_LogPrintfWithFlag("-----[%s][%s][%d] PAUTH CANCELLED ERR END -----", __FILE__, __FUNCTION__, __LINE__);
				return (VS_ERROR);
			} else
			{
				inFUBON_DispHostResponseCode(pobTran); /* 顯示主機回的錯誤訊息 */
				inDISP_LogPrintfWithFlag("-----[%s][%s][%d] PAUTH ERR END -----", __FILE__, __FUNCTION__, __LINE__);
				return (VS_ERROR);
			}

		}

	}		/* 主機授權 */
	else if (pobTran->inTransactionResult == _TRAN_RESULT_AUTHORIZED_)
	{
		/* 主機回傳結果 */
		EMVGlobConfig.uszAction = d_ONLINE_ACTION_APPROVAL;
		/* 要更新端末機的日期及時間 */
		/* [整理程式修改] 重新開啟校時的功能 [SAM] 2022/7/26 下午 2:13 */
		if (inFunc_SetEDCDateTime(pobTran->srBRec.szDate, pobTran->srBRec.szTime) != VS_SUCCESS)
		{
			inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse EMV Auth Sucess Sync Time *Error* Line[%d]", __LINE__);
			return (VS_ERROR);
		}

	}		/* 主機拒絕 */
	else
	{
		/* 主機回傳結果 */
		EMVGlobConfig.uszAction = d_ONLINE_ACTION_DECLINE;

		if (pobTran->inTransactionResult == _TRAN_RESULT_CANCELLED_)
		{

			inSetSendReversalBit("N");
			if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) == VS_ERROR)
			{
				inDISP_DispLogAndWriteFlie(" FU OnlineAnalyse EMV Decline HDPT[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
				return (VS_ERROR);
			}

			inFUBON_DispHostResponseCode(pobTran); /* 顯示主機回的錯誤訊息 */
			inDISP_LogPrintfWithFlag("-----[%s][%s][%d] CANCELLED ERR END -----", __FILE__, __FUNCTION__, __LINE__);
			return (VS_ERROR);
		} else
		{
			inFUBON_DispHostResponseCode(pobTran); /* 顯示主機回的錯誤訊息 */

			inDISP_LogPrintfWithFlag("-----[%s][%s][%d]  ERR END -----", __FILE__, __FUNCTION__, __LINE__);
			return (VS_ERROR);
		}
	}

	inTIME_UNIT_GetRunTimeGlobal(ulRunTime, "inFUBON_OnlineAnalyseEMV END");
	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] END -----", __FILE__, __FUNCTION__, __LINE__);
	return (VS_SUCCESS);
}

int inFUBON_GetSTAN(TRANSACTION_OBJECT *pobTran)
{
	char szSTANNum[12 + 1];

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	memset(szSTANNum, 0x00, sizeof (szSTANNum));
	if (inGetSTANNum(szSTANNum) == VS_ERROR)
	{
		inDISP_DispLogAndWriteFlie(" FU GetSTAN *Error* Line[%d]", __LINE__);
		return (VS_ERROR);
	}

	pobTran->srBRec.lnSTANNum = atol(szSTANNum);

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] END -----", __FILE__, __FUNCTION__, __LINE__);
	return (VS_SUCCESS);
}

/*
Function		: inFUBON_SetSTAN
Date&Time	: 2015/12/24 早上 10:25
Describe		: STAN++
 */
int inFUBON_SetSTAN(TRANSACTION_OBJECT *pobTran)
{
	long lnSTAN;
	char szSTANNum[12 + 1];

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	memset(szSTANNum, 0x00, sizeof (szSTANNum));
	if (inGetSTANNum(szSTANNum) == VS_ERROR)
	{
		inDISP_DispLogAndWriteFlie(" FU GetSTAN *Error* Line[%d]", __LINE__);
		return (VS_ERROR);
	}

	lnSTAN = atol(szSTANNum);
	if (lnSTAN++ > 999999)
		lnSTAN = 1;

	memset(szSTANNum, 0x00, sizeof (szSTANNum));
	sprintf(szSTANNum, "%06ld", lnSTAN);
	if (inSetSTANNum(szSTANNum) == VS_ERROR)
	{
		inDISP_DispLogAndWriteFlie(" FU SetSTAN *Error* Line[%d]", __LINE__);
		return (VS_ERROR);
	}

	if (inSaveHDPTRec(pobTran->srBRec.inHDTIndex) < 0)
	{
		inDISP_DispLogAndWriteFlie(" FU SetSTAN Save Hdt[%d] *Error* Line[%d]", pobTran->srBRec.inHDTIndex, __LINE__);
		return (VS_ERROR);
	}

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] END -----", __FILE__, __FUNCTION__, __LINE__);
	return (VS_SUCCESS);
}

/*
App Name		: inFUBON_CUP_FuncGetCMK
App Builder	: sampo
App Date&Time	: 2013/11/13 
App Function	: CUP CMK
Input Param	: 1.TRANSACTION_OBJECT *pobTran
			  2.Output
Output Param  :  -> Return VS_SUCCESS
 */
int inFUBON_CUP_FuncGetCMK(TRANSACTION_OBJECT *pobTran, char* Output)
{

	char szCurrentDateTime[15 + 1];
	char TempccBuffer[2 + 1];
	char ClearCMK[16 + 1];
	char EncryptBuffer[60];
	char szSTAN[6 + 1], szField11[3 + 1];
	char TempSoftBcdBuf[8 + 1];
	unsigned int Tempcc;
	int inSoftwareKey, i;

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);
	inDISP_LogPrintfWithFlag(" FU GetCMK Date[%s] Time[%s] Line[%d] ", pobTran->srBRec.szDate, pobTran->srBRec.szTime, __LINE__);
		
	if (strlen(pobTran->srBRec.szDate) < 8 || strlen(pobTran->srBRec.szTime) < 6)
	{
		RTC_NEXSYS srRTC;

		memset(&srRTC, 0x00, sizeof (RTC_NEXSYS));
		if (inFunc_GetSystemDateAndTime(&srRTC) != VS_SUCCESS)
			return (VS_ERROR);

		inFunc_Sync_BRec_Date_Time(pobTran, &srRTC);
	}

	memcpy(&szCurrentDateTime[0], pobTran->srBRec.szDate, 8);
	memcpy(&szCurrentDateTime[8], pobTran->srBRec.szTime, 6);

	
	inDISP_LogPrintfWithFlag(" CurrentData[%s] Line[%d]", szCurrentDateTime, __LINE__);

	memset(TempccBuffer, 0x00, sizeof (TempccBuffer));
	memcpy(TempccBuffer, &szCurrentDateTime[12], 2);
	Tempcc = atoi(TempccBuffer);
	Tempcc = ((~Tempcc + 3) * 3) % 100;

	memset(ClearCMK, 0x00, sizeof (ClearCMK));
	memset(TempccBuffer, 0x00, sizeof (TempccBuffer));
	sprintf(TempccBuffer, "%02u", Tempcc);

	sprintf(ClearCMK, "%.14s", szCurrentDateTime);
	strcat(ClearCMK, TempccBuffer);

	inDISP_LogPrintfWithFlag(" FuncGetCMK[%s] Line[%d]", ClearCMK, __LINE__);

	inFUBON_KEK_Write((BYTE *) ClearCMK, 16);

	memset(EncryptBuffer, 0x00, sizeof (EncryptBuffer));
	memcpy(EncryptBuffer, ClearCMK, 16);

	memset(szField11, 0x00, sizeof (szField11));
	memset(szSTAN, 0x00, sizeof (szSTAN));
	sprintf(szSTAN, "%06ld", pobTran->srBRec.lnSTANNum);

	inDISP_LogPrintfWithFlag(" szSTAN[%s] Line[%d]", szSTAN, __LINE__);

	inFunc_ASCII_to_BCD((BYTE *) & szField11[0], &szSTAN[0], 3);
	inSoftwareKey = (unsigned char) szField11[2] & 0x0f;

	for (i = 0; i < 16; i++)
	{
		EncryptBuffer[i] = EncryptBuffer[i] ^ inSoftwareKey;
		inSoftwareKey++;

		if (inSoftwareKey > 9)
			inSoftwareKey = 0;
	}

	memset(TempSoftBcdBuf, 0x00, sizeof (TempSoftBcdBuf));

	inDISP_LogPrintfWithFlag("inFUBON_CUP_FuncGetCMK(%02x%02x%02x%02x%02x%02x%02x%02x) 1!!", EncryptBuffer[0], EncryptBuffer[1], EncryptBuffer[2], EncryptBuffer[3], EncryptBuffer[4], EncryptBuffer[5], EncryptBuffer[6], EncryptBuffer[7]);

	SoftWareTransferPack(EncryptBuffer, 16, TempSoftBcdBuf);

	inDISP_LogPrintfWithFlag("inFUBON_CUP_FuncGetCMK(%02x%02x%02x%02x%02x%02x%02x%02x) 2!!", TempSoftBcdBuf[0], TempSoftBcdBuf[1], TempSoftBcdBuf[2], TempSoftBcdBuf[3], TempSoftBcdBuf[4], TempSoftBcdBuf[5], TempSoftBcdBuf[6], TempSoftBcdBuf[7]);

	inFunc_BCD_to_ASCII(&EncryptBuffer[0], (BYTE *) & TempSoftBcdBuf[0], 8);

	inDISP_LogPrintfWithFlag("inFUBON_CUP_FuncGetCMK 3 = %s", EncryptBuffer);

	memset(Output, 0x00, sizeof (Output));
	memcpy(Output, EncryptBuffer, 16);

	inDISP_LogPrintfWithFlag("inFUBON_CUP_FuncGetCMK Out [%s]", Output);

	inDISP_LogPrintfWithFlag("-----[%s][%s][%d] END-----", __FILE__, __FUNCTION__, __LINE__);
	return (VS_SUCCESS);
}

/*
 * Function		: inFUBON_UserCehckLogon
 * RDate&Time	: 2022/7/25 下午 4:51
 * Return Value	: VS_SUCCESS 執行 CUP LOGON
 *			  VS_USER_CANCEL 使用者取消
 *			  VS_TIMEOUT 畫面計時倒數已結束
 * Describe		: 
 * 新增註解說明，此功能為顯示圖片讓操作者進行是否要進行LOG ON的交易確認
 * 
 */
int inFUBON_UserCehckLogon(TRANSACTION_OBJECT *pobTran)
{
	int inRetVal, inChoice = _DisTouch_No_Event_;
	int inTouchSensorFunc = _Touch_CUP_LOGON_;
	char szKey = 0x00;

	inDISP_ClearAll();
	inFunc_Display_LOGO(0, _COORDINATE_Y_LINE_16_2_); /* 第一層顯示 LOGO */
	inDISP_PutGraphic(_MENU_LOGON_TITLE_, 0, _COORDINATE_Y_LINE_8_3_); /* 第一層顯示 <安全認證> */
	inDISP_PutGraphic(_CHECK_LOGON_FUBON_, 0, _COORDINATE_Y_LINE_8_4_);
	inDISP_BEEP(1, 1);

	/* 抓取 KioskFlag的值，如為 TRUE 就不用確認畫面直接執行 2020/3/6 下午 4:28 [SAM] */
	if (inFunc_GetKisokFlag() == VS_TRUE)
	{
		inDISP_Wait(500);
		return (VS_SUCCESS);
	}

	/* 設定Timeout */
	inDISP_Timer_Start(_TIMER_NEXSYS_1_, _EDC_TIMEOUT_);

	/* 執行下載請按確認，不執行請按清除 */
	while (1)
	{
		inChoice = inDisTouch_TouchSensor_Click_Slide(inTouchSensorFunc);
		szKey = uszKBD_Key();

		/* TimeOut */
		if (inTimerGet(_TIMER_NEXSYS_1_) == VS_SUCCESS)
		{
			szKey = _KEY_TIMEOUT_;
		}

		if (szKey == _KEY_ENTER_ || inChoice == _CUPLogOn_Touch_KEY_1_)
		{
			/* 清除顯示確認或取消的訊息 2022/11/7 [SAM] */
			inDISP_Clear_Line(_LINE_8_4_, _LINE_8_8_);
			inRetVal = VS_SUCCESS;
			break;
		} else if (szKey == _KEY_CANCEL_ || inChoice == _CUPLogOn_Touch_KEY_2_)
		{
			inRetVal = VS_USER_CANCEL;
			break;
		} else if (szKey == _KEY_TIMEOUT_)
		{
			inRetVal = VS_TIMEOUT;
			break;
		}

	}
	/* 清空Touch資料 */
	inDisTouch_Flush_TouchFile();

	return inRetVal;
}

/*
Function        :inFUBON_DispHostResponseCode
Date&Time       :2016/11/15 下午 5:44
Describe        :顯示錯誤代碼
 */
int inFUBON_DispHostResponseCode(TRANSACTION_OBJECT *pobTran)
{
	int inChoice = _DisTouch_No_Event_;
	int inRetVal = VS_SUCCESS;
	char szResponseCode[10 + 1] = {0};
	char szMsg[42 + 1] = {0};
	unsigned char uszKey = 0x00;
	//pobTran->inECRErrorMsg

	memset(szMsg, 0x00, sizeof (szMsg));
	inDISP_LogPrintfWithFlag("inFUBON_DispHostResponseCode 1,%s!!", pobTran->srBRec.szRespCode);

	if ((pobTran->srBRec.szRespCode[0] >= '0' && pobTran->srBRec.szRespCode[0] <= '9') &&
		(pobTran->srBRec.szRespCode[1] >= '0' && pobTran->srBRec.szRespCode[1] <= '9'))
	{
		switch ((pobTran->srBRec.szRespCode[0] - 0x30) * 10 + (pobTran->srBRec.szRespCode[1] - 0x30))
		{
			case 3:
				sprintf(szMsg, "%s", "無效的商店代號");
				break;
			case 12:
				sprintf(szMsg, "%s", "交易不合法");
				break;
			case 13:
				sprintf(szMsg, "%s", "金額不合法");
				break;
			case 14:
				sprintf(szMsg, "%s", "卡片不合法");
				break;
			case 19:
			case 21:
				sprintf(szMsg, "%s", "請重新交易");
				break;
			case 25:
				sprintf(szMsg, "%s", "無原交易紀錄");
				break;
			case 30:
			case 31:
				sprintf(szMsg, "%s", "主機分析電文錯誤");
				break;
			case 41:
				sprintf(szMsg, "%s", "遺失卡");
				break;
			case 43:
				sprintf(szMsg, "%s", "請沒收卡片");
				break;
			case 51:
				sprintf(szMsg, "%s", "餘額不足");
				break;
			case 54:
				sprintf(szMsg, "%s", "卡片已過期");
				break;
			case 55:
				sprintf(szMsg, "%s", "密碼錯誤請重試");
				break;
			case 57:
			case 58:
				sprintf(szMsg, "%s", "交易認證失敗");
				break;
			case 59:
				sprintf(szMsg, "%s", "帳號錯誤");
				break;
			case 61:
				sprintf(szMsg, "%s", "金額過高");
				break;
			case 62:
				sprintf(szMsg, "%s", "請重新交易");
				break;
			case 63:
				sprintf(szMsg, "%s", "主機密碼錯誤");
				break;
			case 75:
				sprintf(szMsg, "%s", "密碼超過次數");
				break;
			case 76:
			case 77:
				sprintf(szMsg, "%s", "請聯絡發卡銀行");
				break;
			case 78:
				sprintf(szMsg, "%s", "交易不存在");
				break;
			case 79:
				sprintf(szMsg, "%s", "批次已開啟");
				break;
			case 80:
				sprintf(szMsg, "%s", "批號錯誤");
				break;
			case 85:
				sprintf(szMsg, "%s", "批號不存在");
				break;
			case 88:
				sprintf(szMsg, "%s", "商店代號錯誤");
				break;
			case 89:
				sprintf(szMsg, "%s", "端末機代號錯誤");
				break;
			case 91:
				sprintf(szMsg, "%s", "請聯絡發卡銀行");
				break;
			case 94:
				sprintf(szMsg, "%s", "交易重覆");
				break;
			case 95:
				sprintf(szMsg, "%s", "批次上傳");
				break;
			case 96:
				sprintf(szMsg, "%s", "主機系統錯誤");
				break;
			default:
				sprintf(szMsg, "%s", "拒絕交易");
				break;
		}
	} else
	{
		if (!memcmp(&pobTran->srBRec.szRespCode[0], "0X", 2))
			sprintf(szMsg, "%s", "拒絕交易"); /* 拒絕交易 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "A0", 2))
			sprintf(szMsg, "%s", "驗証錯誤請重試"); /* 驗証錯誤請重試 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "A1", 2))
			sprintf(szMsg, "%s", "驗証錯誤請重試"); /* 驗証錯誤請重試 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "C8", 2))
			sprintf(szMsg, "%s", "感應交易超額"); /* 感應交易超額 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "C9", 2))
			sprintf(szMsg, "%s", "感應交易超次"); /* 感應交易超次 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XA", 2))
			sprintf(szMsg, "%s", "拒絕交易"); /* 拒絕交易 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XB", 2))
			sprintf(szMsg, "%s", "拒絕交易"); /* 拒絕交易 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XC", 2))
			sprintf(szMsg, "%s", "請勿按銀聯鍵"); /* 請勿按銀聯鍵 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XN", 2))
			sprintf(szMsg, "%s", "請改按銀聯鍵"); /* 請改按銀聯鍵 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XV", 2))
			sprintf(szMsg, "%s", "輸入銀聯背面三碼"); /* 輸入銀聯背面三碼 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XX", 2))
			sprintf(szMsg, "%s", "請改刷磁條"); /* 請改刷磁條 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XY", 2))
			sprintf(szMsg, "%s", "NPS拆帳單"); /* NPS拆帳單 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XZ", 2))
			sprintf(szMsg, "%s", "拒絕交易"); /* 拒絕交易 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "XI", 2))
			sprintf(szMsg, "%s", "拒絕交易"); /* 拒絕交易 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L3", 2))
			sprintf(szMsg, "%s", "優惠已兌換"); /* 優惠已兌換 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L4", 2))
			sprintf(szMsg, "%s", "兌換期限已過"); /* 兌換期限已過 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L5", 2))
			sprintf(szMsg, "%s", "請以刷卡作兌換"); /* 請以刷卡作兌換 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L6", 2))
			sprintf(szMsg, "%s", "請掃描條碼作兌換"); /* 請掃描條碼作兌換 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L7", 2))
			sprintf(szMsg, "%s", "無兌換可取消"); /* 無兌換可取消 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L8", 2))
			sprintf(szMsg, "%s", "重複取消"); /* 重複取消 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L9", 2))
			sprintf(szMsg, "%s", "取消期限已過"); /* 取消期限已過 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "ID", 2))
			sprintf(szMsg, "%s", "ID身分字號錯誤"); /* ID身分字號錯誤 */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "Y1", 2))
			sprintf(szMsg, "%s", "拒絕交易");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "Z1", 2))
			sprintf(szMsg, "%s", "拒絕交易");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "Y3", 2))
			sprintf(szMsg, "%s", "拒絕交易");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "Z3", 2))
			sprintf(szMsg, "%s", "拒絕交易");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "OL", 2))
			sprintf(szMsg, "%s", "拒絕交易");
			/* For Fubon Host RespCode START */
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "CK", 2))
			sprintf(szMsg, "%s", "請重新安全認證");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "CD", 2))
			sprintf(szMsg, "%s", "認證失效");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "RA", 2))
			sprintf(szMsg, "%s", "請聯絡銀行");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "DD", 2))
			sprintf(szMsg, "%s", "請先結帳");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "D1", 2))
			sprintf(szMsg, "%s", "不可分期特店");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "D2", 2))
			sprintf(szMsg, "%s", "期數不符");
		else if (!memcmp(&pobTran->srBRec.szRespCode[0], "L1", 2))
			sprintf(szMsg, "%s", "點數不足");
			/* For Fubon Host RespCode END */
		else
		{
			strcpy(pobTran->srBRec.szRespCode, "05");
			sprintf(szMsg, "%s", "拒絕交易"); /* Display 【拒絕交易】 */
		}
	}

	inDISP_LogPrintfWithFlag(" FU Display szMsg[%s]", szMsg);

	memset(szResponseCode, 0x00, sizeof (szResponseCode));
	sprintf(szResponseCode, "%s", pobTran->srBRec.szRespCode); /* 錯誤代碼 */

	/* 清下排 */
	inDISP_Clear_Line(_LINE_8_4_, _LINE_8_8_);

	inDISP_ChineseFont(szResponseCode, _FONTSIZE_8X16_, _LINE_8_5_, _DISP_CENTER_);
	inDISP_ChineseFont(szMsg, _FONTSIZE_8X16_, _LINE_8_6_, _DISP_CENTER_);

	/* 不需要使用按鍵，等待一秒就離開 20190523  [SAM] */
#if _MACHINE_TYPE_ == _CASTLE_TYPE_UPT1000_
	inDISP_BEEP(1, 0);
	inDISP_Wait(1000);
	inDISP_Clear_Line(_LINE_8_4_, _LINE_8_8_);
#else	

	/* 抓取 KioskFlag的值，如為 TRUE 就不用確認畫面 2020/3/6 下午 4:28 [SAM] */
	if (inFunc_GetKisokFlag() == VS_TRUE)
	{
		inDISP_BEEP(1, 0);
		inDISP_Wait(500);
		inDISP_Clear_Line(_LINE_8_4_, _LINE_8_8_);
		inDISP_LogPrintfWithFlag(" FU Kiosk DispHostResp Line[%d]", __LINE__);
	} else
	{

		inDISP_PutGraphic(_ERR_CLEAR_, 0, _COORDINATE_Y_LINE_8_7_);
		inDISP_BEEP(1, 0);

		inDISP_Timer_Start(_TIMER_NEXSYS_1_, _EDC_TIMEOUT_);
		while (1)
		{
			inChoice = inDisTouch_TouchSensor_Click_Slide(_Touch_BATCH_END_);
			uszKey = uszKBD_Key();
			if (inTimerGet(_TIMER_NEXSYS_1_) == VS_SUCCESS)
			{
				uszKey = _KEY_TIMEOUT_;
			}

			if (uszKey == _KEY_CANCEL_ ||
				inChoice == _BATCH_END_Touch_ENTER_BUTTON_)
			{
				inRetVal = VS_SUCCESS;
				break;
			} else if (uszKey == _KEY_TIMEOUT_)
			{
				inRetVal = VS_SUCCESS;
				break;
			} else
			{
				continue;
			}
		}
		/* 為了強調Timeout時間 */
		inDISP_Clear_Line(_LINE_8_4_, _LINE_8_8_);
		inDisTouch_Flush_TouchFile();
	}
#endif

	return (inRetVal);
}

/*
Function        : inFUBON_SyncHostTerminalDateTime
Date&Time   : 2019/03/14
Describe        : 同步主機時間
 *  TODO: 要再加入檢查功能，想一下要怎麼做
 */
int inFUBON_SyncHostTerminalDateTime(TRANSACTION_OBJECT *pobTran)
{
	char szDebugMsg[100 + 1];

	if (ginDebug == VS_TRUE)
	{
		memset(szDebugMsg, 0x00, sizeof (szDebugMsg));
		sprintf(szDebugMsg, "%s", pobTran->srBRec.szDate);
		inDISP_LogPrintf(szDebugMsg);

		memset(szDebugMsg, 0x00, sizeof (szDebugMsg));
		sprintf(szDebugMsg, "%s", pobTran->srBRec.szTime);
		inDISP_LogPrintf(szDebugMsg);
	}

	inFunc_SetEDCDateTime(pobTran->srBRec.szDate, pobTran->srBRec.szTime);
	return (VS_SUCCESS);
}

/*
Function        : inFUBON_BootingCheckBatchData
Date&Time   : 2020/5/13 上午 10:27
Describe        : 富邦開機時檢查總額
 */
int inFUBON_BootingCheckBatchData(TRANSACTION_OBJECT *pobTran)
{
#ifdef _FUBON_MAIN_HOST_
	int inRecordCnt, i, inContRec = 0;
	long lnTempTotalAmt = 0L;
	ACCUM_TOTAL_REC srAccumRec;

	inDISP_DispLogAndWriteFlie("-----[%s][%s][%d] START -----", __FILE__, __FUNCTION__, __LINE__);

	/* 預設主機為信用卡主機，富邦目前記錄是在 0 的位置 */
	pobTran->srBRec.inHDTIndex = 0;

	memset(&srAccumRec, 0x00, sizeof (srAccumRec));
	if (VS_SUCCESS != inACCUM_GetRecord(pobTran, &srAccumRec))
	{
		/* 如果抓取檔案失敗有可能是還沒做交易，不需要比對  
		 * 如果是檔案真的有問題不應該在這邊處理  * 2020/5/13 上午 11:07 [SAM] */
		inDISP_DispLogAndWriteFlie("  BootCheckBatchData Amt GetRec *Error* Line[%d]", __LINE__);
		return VS_SUCCESS;
	}

	inRecordCnt = inBATCH_GetTotalCountFromBakFile_By_Sqlite(pobTran);
	inContRec = inRecordCnt;
	inDISP_LogPrintfWithFlag(" BootCheckBatchData  AccCnt[%d] RecCnt[%d] Line[%d]", srAccumRec.lnTotalCount, inRecordCnt, __LINE__);

	if (inRecordCnt > 0)
	{
		inBATCH_GetDetailRecords_By_Sqlite_Enormous_START(pobTran);

		for (i = 0; i < inRecordCnt; i++)
		{
			/*. 開始讀取每一筆交易記錄 .*/
			if (inBATCH_GetDetailRecords_By_Sqlite_Enormous_Read(pobTran, i) != VS_SUCCESS)
			{
				/* 如果抓取檔案失敗有可能是還沒做交易，不需要比對  
				 * 如果是檔案真的有問題不應該在這邊處理  * 2020/5/13 上午 11:07 [SAM] */
				inDISP_DispLogAndWriteFlie("  BootCheckBatchData Sqlite Read *Error* ReCnt[%d] LopCnt [%d] Line[%d]", inRecordCnt, i, __LINE__);
				return VS_SUCCESS;
			}

			if (pobTran->srBRec.uszVOIDBit == VS_FALSE)
			{
				switch (pobTran->srBRec.inCode)
				{
					case _SALE_:
					case _SALE_OFFLINE_:
					case _PRE_AUTH_:
					case _INST_SALE_:
					case _REDEEM_SALE_:
						lnTempTotalAmt += pobTran->srBRec.lnTxnAmount;
						break;
					case _TIP_:
						lnTempTotalAmt += (pobTran->srBRec.lnTxnAmount + pobTran->srBRec.lnTipTxnAmount);
						break;
					case _REFUND_:
						lnTempTotalAmt += (0 - pobTran->srBRec.lnTxnAmount);
						break;
					case _ADJUST_:
						lnTempTotalAmt += pobTran->srBRec.lnAdjustTxnAmount;
						break;
					default:
						inDISP_DispLogAndWriteFlie(" BootCheckBatchData AMT_ERR_inCode(%d)", pobTran->srBRec.inCode);
						break;
				} /* End switch () */
			} else
			{
				/* 因為取消還是有記錄，但總額合計的計數會減掉，所以要重新計算 2020/5/14 上午 10:23 [SAM] */
				inContRec--;
			}
		}

		if (lnTempTotalAmt != srAccumRec.llTotalAmount)
		{
			inDISP_DispLogAndWriteFlie("  BootCheckBatchData *Error* TotalAmt[%ld] TempTotalAmt[%ld] Line[%d]", srAccumRec.llTotalAmount, lnTempTotalAmt, __LINE__);
			/* 因為金額不一樣，所以要秀請先結帳 */
			inLoadHDPTRec(0);
			inSetMustSettleBit("Y");
			inSaveHDPTRec(0);
			inFUBON_EnableFuUnBlanceSettleFlag();
			return VS_SUCCESS;
		}
	} else
	{
		/* 如果抓取檔案失敗有可能是還沒做交易，不需要比對  
		 * 如果是檔案真的有問題不應該在這邊處理  * 2020/5/13 上午 11:07 [SAM] */
		inDISP_DispLogAndWriteFlie("  BootCheckBatchData Amt GetTotalCount *Error* Recnt[%d] Line[%d]", inRecordCnt, __LINE__);
		return VS_SUCCESS;
	}

	inDISP_LogPrintfWithFlag(" BootCheckBatchData  inContRec[%d] Line[%d]", inContRec, __LINE__);

	/* 最後比對計算後的總筆數 2020/5/15 上午 10:34 [SAM] */
	if (srAccumRec.lnTotalCount != inContRec)
	{
		inDISP_DispLogAndWriteFlie("  BootCheckBatchData *Error* AccCnt[%d] RecCnt[%d] Line[%d]", srAccumRec.lnTotalCount, inRecordCnt, __LINE__);
		/* 因為筆數不一樣，所以要秀請先結帳 */
		inLoadHDPTRec(0);
		inSetMustSettleBit("Y");
		inSaveHDPTRec(0);
		inFUBON_EnableFuUnBlanceSettleFlag();
		return VS_SUCCESS;
	}
#endif
	inDISP_DispLogAndWriteFlie("-----[%s][%s][%d] END -----", __FILE__, __FUNCTION__, __LINE__);
	return (VS_SUCCESS);
}

/*
Function        : inFUBON_EnableFuUnBlanceSettleFlag
Date&Time   : 2020/5/13 上午 10:27
Describe        : 開啟不平帳設定
 */
int inFUBON_EnableFuUnBlanceSettleFlag()
{
	ginFuUnBlanceSettleFlag = 1;
	return VS_SUCCESS;
}

/*
Function        : inFUBON_DisableFuUnBlanceSettleFlag
Date&Time   : 2020/5/13 上午 10:27
Describe        : 關閉不平帳設定,因為需要放在Function Point,所以要加參數 pobTran
 */
int inFUBON_DisableFuUnBlanceSettleFlag(TRANSACTION_OBJECT *pobTran)
{
	ginFuUnBlanceSettleFlag = 0;
	return VS_SUCCESS;
}

/*
Function        : inFUBON_GetFuUnBlanceSettleFlag
Date&Time   : 2020/5/13 上午 10:27
Describe        : 抓取是否開啟不平帳的設定
 */
int inFUBON_GetFuUnBlanceSettleFlag()
{
	return ginFuUnBlanceSettleFlag;
}

/*
Function        : inFUBON_DispFuUnBlanceSettleMsg
Date&Time   : 2020/5/13 上午 10:27
Describe        : 顯示請先結帳訊息
 */
int inFUBON_DispFuUnBlanceSettleMsg()
{
	inDISP_Msg_BMP(_ERR_MUST_SETTLE_, _COORDINATE_Y_LINE_8_6_, _CLEAR_KEY_MSG_, _EDC_TIMEOUT_, _HOST_NAME_CREDIT_FUBON_, _LINE_8_5_);
	return VS_SUCCESS;
}

int inFUBON_PackField35Data(TRANSACTION_OBJECT *pobTran, char* szPackData, int inPackszServiceCode)
{
	
	if(inPackszServiceCode)
	{		
		if (!memcmp(&pobTran->srBRec.szTranAbbrev[0], "NC", 2) && 
			!memcmp(&pobTran->srBRec.szServiceCode[0], "701", 3))
		{
			memcpy(szPackData, &pobTran->srBRec.szPAN[4], 11);
			strcat(szPackData, "D");
			strcat(szPackData, pobTran->srBRec.szExpDate);
			strcat(szPackData, pobTran->srBRec.szServiceCode);
		} else
		{
			strcpy(szPackData, pobTran->srBRec.szPAN);
			strcat(szPackData, "D");
			strcat(szPackData, pobTran->srBRec.szExpDate);
			strcat(szPackData, pobTran->srBRec.szServiceCode);
		}
		
		
	}else{
		/* Manual keyin -> PAN + 'D' + Expire Date */
		if (!memcmp(&pobTran->srBRec.szTranAbbrev[0], "NC", 2))
		{
			memcpy(szPackData, &pobTran->srBRec.szPAN[4], 11);
			strcat(szPackData, "D");
			strcat(szPackData, pobTran->srBRec.szExpDate);
		} else
		{
			strcpy(szPackData, pobTran->srBRec.szPAN);
			strcat(szPackData, "D");
			strcat(szPackData, pobTran->srBRec.szExpDate);
		}
	}
	return VS_SUCCESS;
}



