#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctosapi.h>
#include "../INCLUDES/Define_1.h"
#include "../INCLUDES/Transaction.h"
#include "../PRINT/Print.h"
#include "../DISPLAY/Display.h"
#include "../FUNCTION/Function.h"
#include "../FUNCTION/FuncTable.h"
#include "Flow.h"

extern int ginDebug; /* Debug使用 extern */
extern int ginFindRunTime;

/* 只可刷卡，不開晶片 */
int SALE_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

/* 可刷卡、也可插卡 */
int SALE_ICC_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int SALE_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int SALE_CTLS_IDLE_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_IDLE_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int FISC_SALE_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FISC_,
	_FLOW_NULL_,
};

int FISC_SALE_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_FISC_CTLS_,
	_FLOW_NULL_,
};

int INST_SALE_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	/*_FUNCTION_GET_CARD_FIELDS_CTLS_,*/
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int INST_REFUND_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTPAYMENT_,
	//_CREDIT_FUNCTION_GET_OPT_INSTFEE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

/* 富邦 Statin 才會有分期調帳功能  2022/10/21 [SAM]*/
int INST_ADJUST_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

/* 富邦 Statin 才會有分期調帳功能  2022/10/21 [SAM]*/
int INST_ADJUST_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTFEE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int REDEEM_SALE_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	/*_FUNCTION_GET_CARD_FIELDS_CTLS_,*/
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int REDEEM_REFUND_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_OPT_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

/* 富邦 Statin 才會有紅利調帳功能  2022/10/21 [SAM]*/
int REDEEM_ADJUST_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

/* 富邦 Statin 才會有紅利調帳功能  2022/10/21 [SAM]*/
int REDEEM_ADJUST_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int VOID_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_USER_CHOICE_,
	_FLOW_NULL_,
};

int REFUND_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};


int REFUND_AMOUNT_FIRST_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int REFUND_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};


int REFUND_AMOUNT_FIRST_CUP_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};



int REFUND_CTLS_CUP_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int FISC_REFUND_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FISC_,
	_CREDIT_FUNCTION_GET_OPT_FISC_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_FISC_RRN_,
	_CREDIT_FUNCTION_GET_OPT_FISC_REFUND_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FLOW_NULL_,
};

int FISC_REFUND_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_FISC_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_FISC_RRN_,
	_CREDIT_FUNCTION_GET_OPT_FISC_REFUND_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_FISC_REDEND_CTLS_,
	_FLOW_NULL_,
};

int SETTLE_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_CREDIT_FUNCTION_CHECK_RESULT_SETTLE_,
	_FLOW_NULL_,
};

int TIP_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_USER_CHOICE_,
	_FLOW_NULL_,
};

int SALE_OFFLINE_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int SALE_OFFLINE_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int ADJUST_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_USER_CHOICE_,
	_FLOW_NULL_,
};

int PRE_AUTH_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int PRE_AUTH_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

/* [新增預授權完成] 修改富邦預先授權完成流程 2022/5/11 [SAM] */
#if defined(_FUBON_MAIN_HOST_)

int PRE_COMP_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_PREAUTH_AMOUNT_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int PRE_COMP_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_PREAUTH_AMOUNT_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

#else

int PRE_COMP_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};

int PRE_COMP_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	/*_CREDIT_FUNCTION_GET_OPT_ORI_PREAUTH_AMOUNT_,*/
	_CREDIT_FUNCTION_GET_OPT_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_,
};
#endif

int MAIL_ORDER_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CREDIT_CARD_FIELDS_MAIL_ORDER_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_CREDIT_FUNCTION_GET_CVV2_,
	_FLOW_NULL_,
};

int LOYALTY_REDEEM_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_LOYALTY_REDEEM_,
	_FUNCTION_CHECK_PAN_EXPDATE_LOYALTY_REDEEM_,
	_FLOW_NULL_,
};

int LOYALTY_REDEEM_CTLS_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_CARD_FIELDS_LOYALTY_REDEEM_CTLS_,
	_FUNCTION_CHECK_PAN_EXPDATE_LOYALTY_REDEEM_,
	_FLOW_NULL_,
};

int BARCODE_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_BARCODE_,
	_FUNCTION_CHECK_BARCODE_LOYALTY_REDEEM_,
	_FLOW_NULL_,
};

int VOID_LOYALTY_REDEEM_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_BARCODE_,
	_FUNCTION_CHECK_BARCODE_LOYALTY_REDEEM_,
	_FLOW_NULL_,
};

int PRINT_TOTAL_OPERATION_BY_BUFFER_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_PRINT_TOTAL_REPORT_BY_BUFFER_,
	_FLOW_NULL_,
};

int PRINT_DETAIL_OPERATION_BY_BUFFER_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_PRINT_DETAIL_REPORT_BY_BUFFER_,
	_FLOW_NULL_,
};

int DELETE_BATCH_OPERATION_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_DELETE_BATCH_FLOW_,
	_FUNCTION_DELETE_ACCUM_FLOW_,
	_FUNCTION_REST_BATCH_INV_,
	_FUNCTION_UPDATE_BATCH_NUM_,
	_FLOW_NULL_,
};

int PRINT_PARAM_TERM_BYBUFFER_TABLE[] ={
	_CREDIT_FUNCTION_PRINT_PARAM_TERM_BY_BUFFER_,
	_FLOW_NULL_,
};

int PRINT_DCC_PARAM_TERM_BYBUFFER_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_PRINT_DCC_PARAM_BY_BUFFER_,
	_FLOW_NULL_,
};

int SIGNPAD_TEST_TABLE[] ={
	_FUNCTION_GET_SIGNPAD_,
	_FLOW_NULL_,
};

int FUN5_TMS_DOWNLOAD_TABLE[] ={
	_FUNCTION_All_HOST_MUST_SETTLE,
	_FUNC5_TMS_SELECT_FLOW_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_FLOW_,
	_FUNCTION_TMS_RESULT_HANDLE_,
	_FUNCTION_TMS_DISCONNECT_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,
};

int FUN5_RETURN_TASK_REPORT_TABLE[] ={
	_FUNCTION_All_HOST_MUST_SETTLE,
	_FUNC5_TASK_REPORT_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_,
	_FUNCTION_TMS_PRINT_RETURN_TASK_,
	_FUNCTION_TMS_DISCONNECT_,
	_FLOW_NULL_,
};

int FUN5_DCC_DOWNLOAD_TABLE[] ={
	_FUNC5_DCC_DOWNLOAD_PARAMETER_,
	_FLOW_NULL_,
};

int FUN6_TMS_DOWNLOAD_TABLE[] ={
	_FUNCTION_All_HOST_MUST_SETTLE,
	_FUN6_TMS_DOWNLOAD_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_FLOW_,
	_FUNCTION_TMS_RESULT_HANDLE_,
	_FUNCTION_TMS_DISCONNECT_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,
};

int FUN6_TMS_TRACELOG_UPLOAD_TABLE[] ={
	_FUN6_TRACELOG_UPLOAD_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_,
	_FUNCTION_TMS_DISCONNECT_,
	_FLOW_NULL_,
};

int FUN6_DCC_DOWNLOAD_TABLE[] ={
	_FUNC5_DCC_DOWNLOAD_PARAMETER_,
	_FLOW_NULL_,
};

/* 目前用不到，先拿掉 2019/03/13 [SAM] */
#if 0
int FUN6_DCC_RATE_DOWNLOAD_TABLE[] ={
	_NCCC_DCC_FUNCTION_EXCHANGE_RATE_DOWNLOAD_,
	_FLOW_NULL_,
};

/* NCCC tSAM 註冊 */
int TSAM_OPERATION_TABLE[] ={
	_NCCC_FUNCTION_SHOW_REGISTER_MENU_,
	_FLOW_NULL_,
};
#endif
/* 交易查詢 */
int REVIEW_OPRATION_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_REVIEW_,
	_FLOW_NULL_,
};

/* 總額查詢 */
int REVIEW_TOTAL_OPRATION_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_TOTAL_REVIEW_,
	_FLOW_NULL_,
};

/* 明細查詢 */
int REVIEW_DETAIL_OPRATION_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_DETAIL_REVIEW_NEWUI_,
	_FLOW_NULL_,
};

/* 重印帳單 */
int REPRINT_OPERATION_TABLE[] ={
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_USER_CHOICE_,
	_FUNCTION_REPRINT_RECEIPT_BY_BUFFER_,
	/*_NEXSYS_ESC_UPDATE_RE_PRINT_,  重印時要加總紙本數量，另外統計用 20181220 [SAM] */
	_FLOW_NULL_,
};

int FUN1_READERINIT_TABLE[] ={
	_CTLS_INIT_,
	_FLOW_NULL_,
};

/* ECR連線 */
int ECR_TRANSACTION_TABLE[] ={
	_FUNCTION_ECR_RECEIVE_TRANSACTION_REQUEST_,
	_FUNCTION_ECR_CUSTOMER_FLOW_,
        _FUNCTION_ECR_CUSTOMER_FLOW2_,
	_FLOW_NULL_,
};

/* 當外接設備 */
int MULTIFUNC_SLAVE_TRANSACTION_TABLE[] ={
	_MULTIFUNC_RC_COMMAND_,
	_MULTIFUNC_SEND_RESULT_,
	_FLOW_NULL_,
};

/* ESC IDLE 上傳 */
int ESC_UPLOAD_IDLE_TABLE[] ={
	//	_NCCC_ESC_UPLOAD_IDLE_,
	_FLOW_NULL_,
};


/* TMS排程詢問 */
int TMS_SCHEDULE_INQUIRE_TABLE[] ={
	_FUNCTION_TMS_SCHEDULE_INQUIRE_,
	_FLOW_NULL_,
};

/* TMS排程下載 */
int TMS_SCHEDULE_DOWNLOAD_TABLE[] ={
	//	_FUNCTION_TMS_SCHEDULE_DOWNLOAD_,
	_FUNCTION_TMS_DOWNLOAD_SETTLE_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,
};

/* TMS參數生效 */
int TMS_PROCESS_EFFECTIVE_TABLE[] ={
	_FUNCTION_All_HOST_MUST_SETTLE,
	_FUNCTION_TMS_IDLE_UPDATE_,
	_FLOW_NULL_,
};


int I_R_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_SELECT_I_R_PAYMENT_TYPE_,
	_FLOW_NULL_,
};

/* BOOTING 開機流程   */
int EDC_BOOTING_TABLE[] ={
	_EDC_BOOTING_DISPLAY_INITIAL_, /* 顯示函式庫初始化 */
	_EDC_BOOTING_PRINT_INITIAL_, /* 列印函式庫初始化 */
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_, /* 虹堡函式庫初始化 */
	_EDC_BOOTING_UPDATE_PARAMETER_POWER_ON_, /* 檢查是否需更新 */
	_EDC_BOOTING_CLEAR_AP_DUMP_, /* 清空AP下載暫存資料，因更新完會直接重開機所以有暫存檔案 */
	_EDC_BOOTING_PRINT_IMAGE_INITIAL_, /* 抓圖片高度，要放更新之後 */
	_EDC_BOOTING_LOAD_TABLE_, /* load Table, ex: CFGT、EDC */
	_EDC_BOOTING_SYNC_DEBUG_, /* 同步Debug Flag */
	_EDC_BOOTING_COMM_INITIAL_, /* 通訊初始化 */
	_EDC_BOOTING_UPDATE_SUCCESS_REPORT_, /* 檢查是否要回傳生效回報 */
	_EDC_BOOTING_TMSOK_CHECK_INITIAL_, /* 確認是否有下TMS */
//	_EDC_BOOTING_TMS_DCC_SCHEDULE_,	/* TMS連動DCC下載，若有TMS有開DCC，會自動下載 因為富邦沒有DCC，所以拿掉 20190213 [SAM]*/
	_FUNCTION_TMS_REBOOT_, /* TMS下載完需要重開機更新，會在這裡 */
	_EDC_BOOTING_PROCESS_CRADLE_, /* 若有底座連底座的藍芽 */
	_EDC_BOOTING_SQLITE_INITIAL_, /* SQLite初始化 */
	_EDC_BOOTING_ECR_INITIAL_, /* ECR初始化 */
#ifdef __MUTI_FUCN_TEST_
	_EDC_BOOTING_MULTI_FIRST_INITIAL_, /* MULTI初始化 */
#endif
	_EDC_BOOTING_EMV_INITIAL_, /* EMV初始化 */
	_EDC_BOOTING_TSAM_INITIAL_, /* 註冊及PowerOn tSAM */
	_EDC_BOOTING_REPRINT_POWEROFF_, /* 印出斷電的簽單 */
	_EDC_BOOTING_ETICKET_INITIAL_, /* 初始化票證  [新增電票悠遊卡功能] 內容修改為財金版本流程 [SAM] 2022/6/9 上午 11:23  */
	_EDC_BOOTING_CTLS_INITIAL_, /* 初始化感應，感應初始化要放票證後面，不然會被覆蓋設定(這個指虹堡整合的API) */
	_EDC_BOOTING_CUP_LOGON_, /* 安全認證 CUP LOGON */
	_EDC_BOOTING_POWER_ON_PASSWORD_, /* 輸入開機密碼 */
	_FLOW_NULL_,
};

int EDC_LOAD_KEY_BOOTING_TABLE[] ={
	_EDC_BOOTING_DISPLAY_INITIAL_, /* 顯示函式庫初始化 */
	_EDC_BOOTING_PRINT_INITIAL_, /* 列印函式庫初始化 */
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_, /* 虹堡函式庫初始化 */
	_EDC_BOOTING_LOAD_TABLE_, /* load Table, ex: CFGT、EDC */
	_EDC_BOOTING_SYNC_DEBUG_, /* 同步Debug Flag */
	_EDC_BOOTING_COMM_INITIAL_, /* 通訊初始化 */
	_EDC_BOOTING_SQLITE_INITIAL_, /* SQLite初始化 */
	_EDC_BOOTING_ECR_INITIAL_, /* ECR初始化 */
	_FLOW_NULL_,
};

/* BOOTING 開機流程 */
int EDC_V3UL_BOOTING_TABLE[] ={
	_EDC_BOOTING_DISPLAY_INITIAL_, /* 顯示函式庫初始化 */
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_, /* 虹堡函式庫初始化 */
	_EDC_BOOTING_LOAD_TABLE_, /* load Table, ex: CFGT、EDC */
	_EDC_BOOTING_SYNC_DEBUG_, /* 同步Debug Flag */
	_EDC_BOOTING_COMM_INITIAL_, /* 通訊初始化 */
	_EDC_BOOTING_SQLITE_INITIAL_, /* SQLite初始化 */
	_EDC_BOOTING_POWER_ON_PASSWORD_, /* 輸入開機密碼 */
	_EDC_BOOTING_TMSOK_CHECK_INITIAL_, /* 確認是否有下TMS */
	_EDC_BOOTING_MULTI_FIRST_INITIAL_, /* ECR初始化 */
	_EDC_BOOTING_EMV_INITIAL_, /* EMV初始化 */
	_EDC_BOOTING_TSAM_INITIAL_, /* 註冊及PowerOn tSAM */
	_EDC_BOOTING_CTLS_INITIAL_, /* 初始化感應，感應初始化要放票證後面，不然會被覆蓋設定 */
	_FLOW_NULL_,
};

/* REBOOT 重新開機 */
int EDC_REBOOT_TABLE[] ={
	_FLOW_NULL_,
};

/* 省電睡眠流程 */
int POWER_SAVING_SLEEP_TABLE[] ={
	_POWER_SAVING_FLOW_SLEEP_,
	_FLOW_NULL_,
};

/* 省電流程 */
int POWER_SAVING_STANDBY_TABLE[] ={
	_POWER_SAVING_FLOW_STANDBY_,
	_FLOW_NULL_,
};

/* 票證消費扣款 */
int TICKET_DEDUCT_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證查詢餘額 */
int TICKET_CHECK_BALANCE_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證加值餘額 */
int TICKET_TOPUP_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證退貨 */
int TICKET_REFUND_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_ESVC_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_RF_NUMBER_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證加值取消 */
int TICKET_VOID_TOP_UP_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_TICKET_GET_VOID_TOP_UP_AMOUNT_FROM_BATCH_,
	_FLOW_NULL_,
};

/* 票證 SAM 註冊 */
int TICKET_SAM_REGISTER_OPERATION_TABLE[] ={
	_TICKET_FUNC_IPASS_REGISTER_,
	_FLOW_NULL_,
};

int LOAD_KEY_FROM_520_TABLE[] ={
	_FUNCTION_ECR_LOAD_TMK_,
	_FLOW_NULL_,
};

/* 只可刷卡，不開晶片 */
int FUBON_LOGON_OPERATION_TABLE[] ={
	_EDC_BOOTING_CUP_LOGON_,
	_FLOW_NULL_,
};


/* 彥均加的TMS 需全部加入  20190108 [SAM]  START*/
int FUN5_NEXSYS_TMS_DOWNLOAD_TABLE[] ={
	_FUNCTION_All_HOST_MUST_SETTLE,
	_FUNCTION_NEXSYS_TMS_SELECT_FLOW_,
	//	_FUNCTION_NEXSYS_TMS_CONNECT_, /* 因為聯合原本需要從ISO下載FTP的IP，所以才需要這個步驟 */
	_FUNCTION_NEXSYS_TMS_SEND_RECEIVE_FLOW_,
	_FUNCTION_NEXSYS_TMS_RESULT_HANDLE_,
	_FLOW_NULL_,
};



int SELFSERVE_AUTHCOM_OPERATION_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_USER_CHOICE_,
	_FLOW_NULL_,
};


/* [新增電票悠遊卡功能]  新增CMASMenu時需要的執行步驟 [SAM] 2022/6/9 下午 4:37 */
/* 悠遊卡消費扣款、退貨、現金加值 */
int CMAS_DEDUCT_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_CMAS_,
	_CMAS_CHECK_TRANS_ENABLE_, /*20200521 Added [Hachi]*/
	// _TICKET_DISPLAY_LOGON_RESULT_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	// _TICKET_GET_ESVC_CARD_FLOW_,  
	_CMAS_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};
/*2020/1/15 上午 11:02 悠遊卡餘額查詢與結帳*/
int CMAS_NORMAL_TABLE[] ={
	_FUNCTION_CHECK_TERM_STATUS_CMAS_,
	_CMAS_CHECK_TRANS_ENABLE_, /*20200521 Added [Hachi]*/
	_CMAS_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

int CMAS_VOID_TABLE[] ={
	// _FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_CMAS_,
	_CMAS_CHECK_TRANS_ENABLE_, /*20200521 Added [Hachi]*/
	// _TICKET_DISPLAY_LOGON_RESULT_,
	// _CREDIT_FUNCTION_GET_OPT_STOREID_,
	// _CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	// _TICKET_GET_ESVC_CARD_FLOW_,  
	_CMAS_DECIDE_TRANS_TYPE_,
	_TICKET_GET_VOID_TOP_UP_AMOUNT_FROM_BATCH_,
	_FLOW_NULL_,
};
/* [新增電票悠遊卡功能]  新增CMASMenu時需要的執行步驟 [SAM] 2022/6/9 下午 4:37 END */

/* [新增SVC功能]  [SAM] */
int SVC_CARD_OPERATION[] ={
	_FUNCTION_CHECK_TERM_STATUS_,
	_SVC_TMS_DOWNLOAD_,
	_FUNCTION_GET_SVC_CARD_FIELDS_CTLS_,/* TODO: 這裏需要看支援的方法，可能要改成只有感應  2022/12/26 */
	_FLOW_NULL_,
};


OPT_TABLE OPERATION_TABLE[] ={
	{_OPERATION_MULTIFUNC_SLAVE_, MULTIFUNC_SLAVE_TRANSACTION_TABLE},
	{_OPERATION_SALE_, SALE_OPERATION_TABLE},
	{_OPERATION_SALE_ICC_, SALE_ICC_OPERATION_TABLE},
	{_OPERATION_SALE_CTLS_, SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_SALE_CTLS_IDLE_, SALE_CTLS_IDLE_OPERATION_TABLE},
	{_OPERATION_FISC_SALE_, FISC_SALE_OPERATION_TABLE},
	{_OPERATION_FISC_SALE_CTLS_, FISC_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_INST_SALE_CTLS_, INST_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_INST_REFUND_CTLS_, INST_REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_INST_ADJUST_, INST_ADJUST_OPERATION_TABLE},
	{_OPERATION_INST_ADJUST_CTLS_, INST_ADJUST_CTLS_OPERATION_TABLE},
	{_OPERATION_REDEEM_SALE_CTLS_, REDEEM_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_REDEEM_REFUND_CTLS_, REDEEM_REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_REDEEM_ADJUST_, REDEEM_ADJUST_OPERATION_TABLE},//2022/10/21 目前有在用
	{_OPERATION_REDEEM_ADJUST_CTLS_, REDEEM_ADJUST_CTLS_OPERATION_TABLE},
	{_OPERATION_VOID_, VOID_OPERATION_TABLE},
	{_OPERATION_REFUND_, REFUND_OPERATION_TABLE},
	{_OPERATION_REFUND_AMOUNT_FIRST_, REFUND_AMOUNT_FIRST_OPERATION_TABLE},
	{_OPERATION_REFUND_CTLS_, REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_REFUND_AMOUNT_FIRST_CUP_, REFUND_AMOUNT_FIRST_CUP_OPERATION_TABLE},
	{_OPERATION_REFUND_CTLS_CUP_, REFUND_CTLS_CUP_OPERATION_TABLE},
	{_OPERATION_FISC_REFUND_, FISC_REFUND_OPERATION_TABLE},
	{_OPERATION_FISC_REFUND_CTLS_, FISC_REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_SETTLE_, SETTLE_OPERATION_TABLE},
	{_OPERATION_TIP_, TIP_OPERATION_TABLE},
	{_OPERATION_SALE_OFFLINE_, SALE_OFFLINE_OPERATION_TABLE},
	{_OPERATION_SALE_OFFLINE_CTLS_, SALE_OFFLINE_CTLS_OPERATION_TABLE},
	{_OPERATION_ADJUST_, ADJUST_OPERATION_TABLE},
	{_OPERATION_PRE_AUTH_, PRE_AUTH_OPERATION_TABLE},
	{_OPERATION_PRE_AUTH_CTLS_, PRE_AUTH_CTLS_OPERATION_TABLE},
	{_OPERATION_PRE_COMP_, PRE_COMP_OPERATION_TABLE},
	{_OPERATION_PRE_COMP_CTLS_, PRE_COMP_CTLS_OPERATION_TABLE},
	{_OPERATION_MAIL_ORDER_, MAIL_ORDER_OPERATION_TABLE},
	{_OPERATION_LOYALTY_REDEEM_, LOYALTY_REDEEM_OPERATION_TABLE},
	{_OPERATION_LOYALTY_REDEEM_CTLS_, LOYALTY_REDEEM_CTLS_OPERATION_TABLE},
	{_OPERATION_BARCODE_, BARCODE_OPERATION_TABLE},
	{_OPERATION_VOID_LOYALTY_REDEEM_, VOID_LOYALTY_REDEEM_OPERATION_TABLE},
	{_OPERATION_TOTAL_REPORT_, PRINT_TOTAL_OPERATION_BY_BUFFER_TABLE},// 2022/10/21 有在使用
	{_OPERATION_DETAIL_REPORT_, PRINT_DETAIL_OPERATION_BY_BUFFER_TABLE},// 2022/10/21 有在使用
	{_OPERATION_DELETE_BATCH_, DELETE_BATCH_OPERATION_TABLE},
	{_OPERATION_REVIEW_, REVIEW_OPRATION_TABLE},
	{_OPERATION_REVIEW_TOTAL_, REVIEW_TOTAL_OPRATION_TABLE},
	{_OPERATION_REVIEW_DETAIL_, REVIEW_DETAIL_OPRATION_TABLE},
	{_OPERATION_REPRINT_, REPRINT_OPERATION_TABLE},
//	{_OPERATION_TSAM_,				TSAM_OPERATION_TABLE},
	{_OPERATION_FUN7_PRINT_, PRINT_PARAM_TERM_BYBUFFER_TABLE},
	{_OPERATION_FUN7_DCC_PRINT_, PRINT_DCC_PARAM_TERM_BYBUFFER_TABLE},
	{_OPERATION_FUN4_PRINT_, SIGNPAD_TEST_TABLE},
	{_OPERATION_FUN5_TMS_DOWNLOAD_, FUN5_TMS_DOWNLOAD_TABLE},
	{_OPERATION_FUN5_TMS_TASK_REPORT_, FUN5_RETURN_TASK_REPORT_TABLE},
	{_OPERATION_FUN5_DCC_DOWNLOAD_, FUN5_DCC_DOWNLOAD_TABLE},
	{_OPERATION_FUN6_TMS_DOWNLOAD_, FUN6_TMS_DOWNLOAD_TABLE},
	{_OPERATION_FUN6_TMS_TRACELOG_UP_, FUN6_TMS_TRACELOG_UPLOAD_TABLE},
	{_OPERATION_FUN6_DCC_DOWNLOAD_, FUN6_DCC_DOWNLOAD_TABLE},
//	{_OPERATION_FUN6_DCC_RATE_DOWNLOAD_,		FUN6_DCC_RATE_DOWNLOAD_TABLE},
	{_OPERATION_FUN1_READERINIT_, FUN1_READERINIT_TABLE},
	{_OPERATION_ECR_TRANSACTION_, ECR_TRANSACTION_TABLE},
	{_OPERATION_ESC_IDLE_UPLOAD_, ESC_UPLOAD_IDLE_TABLE},
//	{_OPERATION_DCC_SCHEDULE_,			DCC_SCHEDULE_TABLE},
//	{_OPERATION_TMS_DCC_SCHEDULE_,			TMS_DCC_SCHEDULE},
	{_OPERATION_TMS_SCHEDULE_INQUIRE_, TMS_SCHEDULE_INQUIRE_TABLE},
	{_OPERATION_TMS_SCHEDULE_DOWNLOAD_, TMS_SCHEDULE_DOWNLOAD_TABLE},
	{_OPERATION_TMS_PROCESS_EFFECTIVE_, TMS_PROCESS_EFFECTIVE_TABLE},


	{_OPERATION_I_R_, I_R_OPERATION_TABLE},

	{_OPERATION_EDC_BOOTING_, EDC_BOOTING_TABLE}, /* 目前有在用 20190619 [SAM] */
	{_OPERATION_EDC_LOAD_KEY_BOOTING_, EDC_LOAD_KEY_BOOTING_TABLE},
	{_OPERATION_EDC_V3UL_BOOTING_, EDC_V3UL_BOOTING_TABLE},
	{_OPERATION_EDC_REBOOT_, EDC_REBOOT_TABLE},
	{_OPERATION_POWER_SAVING_SLEEP_, POWER_SAVING_SLEEP_TABLE},
	{_OPERATION_POWER_SAVING_STANDBY_, POWER_SAVING_STANDBY_TABLE},
	{_OPERATION_TICKET_DEDUCT_, TICKET_DEDUCT_TABLE},
	{_OPERATION_TICKET_INQUIRY_, TICKET_CHECK_BALANCE_TABLE},
	{_OPERATION_TICKET_TOP_UP_, TICKET_TOPUP_TABLE},
	{_OPERATION_TICKET_REFUND_, TICKET_REFUND_TABLE},
	{_OPERATION_TICKET_VOID_TOP_UP_, TICKET_VOID_TOP_UP_TABLE},
	{_OPERATION_TICKET_SAM_REGISTER_, TICKET_SAM_REGISTER_OPERATION_TABLE},
	{_OPERATION_LOAD_KEY_FROM_520_, LOAD_KEY_FROM_520_TABLE},
	{_OPERATION_CUP_LOGON_, FUBON_LOGON_OPERATION_TABLE},
	{_OPERATION_TMS_DOWNLOAD_, FUN5_NEXSYS_TMS_DOWNLOAD_TABLE}, /*  20190131 TMS [SAM] */
	{_OPERATION_SELFSERVE_AUTHCOM_, SELFSERVE_AUTHCOM_OPERATION_TABLE}, /* 玉山自助用,因需要抓取記錄所以要重寫  2020/12/28 下午 3:26 */
	/* [新增電票悠遊卡功能]  [SAM]  2022/6/8 下午 5:57*/
	// TODO: 這個功能看要不要做, 看起來像開機時在初始化, 但原本初始化已有功能
//	{_OPERATION_EDC_SDK_INITIAL_BOOTING_,           EDC_SDK_INITIAL_BOOTING_TABLE},
	/* [新增電票悠遊卡功能]  新增CMASMenu時需要的執行步驟 [SAM] 2022/6/9 下午 4:37 */
	{_OPERATION_EASYCARD_DEDUCT_, CMAS_DEDUCT_TABLE},
	{_OPERATION_EASYCARD_NORMAL_, CMAS_NORMAL_TABLE},
	{_OPERATION_EASYCARD_VOID_, CMAS_VOID_TABLE},
	/* [新增電票悠遊卡功能]  新增CMASMenu時需要的執行步驟 [SAM] 2022/6/9 下午 4:37 ENDI*/
	/* [新增SVC功能]  [SAM] */
	{_OPERATION_SVC_CARD_,	SVC_CARD_OPERATION},
	
	{_FLOW_NULL_, NULL}
	/*inOPTCode					*inOPTID*/
};

int inFLOW_RunFunction(TRANSACTION_OBJECT *pobTran, int inFuncID)
{
	int i, inRetVal;

	for (i = 0;; i++)
	{
		if (FunctionTable[i].inFuncId == 0)
		{
			return (VS_ERROR);
		} else if (FunctionTable[i].inFuncId == inFuncID)
		{
			inRetVal = FunctionTable[i].inFunctionPoint(pobTran);
			break;
		}
	}

	return (inRetVal);
}

/* TODO: 2022/07/22 要開始看這個 */
int inFLOW_RunOperation(TRANSACTION_OBJECT *pobTran, int inOPTCode)
{
	int *inOPTID = NULL;
	int i, inRetVal = VS_ERROR;
#if (_MACHINE_TYPE_ == _CASTLE_TYPE_UPT1000_)
	BYTE Led[] = {d_LED_MSR, d_LED_ICC, 0xFF};
	BYTE Led2[] = {d_LED_MSR, 0xFF};
#endif

	/* 決定要跑哪個operation table */
	for (i = 0;; i++)
	{
		if (OPERATION_TABLE[i].inOPTCode == inOPTCode)
		{
			inOPTID = OPERATION_TABLE[i].inOPTID;
			break;
		} else if (OPERATION_TABLE[i].inOPTCode == _FLOW_NULL_)
			break;
	}

	if (inOPTID == NULL)
	{
		return (VS_ERROR);
	}

	/* 補註解:
	 *  因 inOPTID 結構最後一個元素會設定為 _FLOW_NULL_ 
	 * 所以 inRetVal 的值，會以執行的 inOPTID 功能時最後執行結果為回覆值 2022/9/30 [SAM] */
	for (i = 0;; i++)
	{
		if (inOPTID[i] == _FLOW_NULL_)
			break;
		/* 新補充UPT說明及新增退貨 [ _FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_ ]條件 2022/2/18 [SAM] */
#if (_MACHINE_TYPE_ == _CASTLE_TYPE_UPT1000_)
		/* UPT 開啟刷卡與磁條的燈*/
		if (inOPTID[i] == _FUNCTION_GET_CARD_FIELDS_CTLS_)
		{
			inDISP_TrunOnOffLightOnPanel(Led, _LIGHT_ON_);
		} else if (inOPTID[i] == _FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_)
		{
			inDISP_TrunOnOffLightOnPanel(Led2, _LIGHT_ON_);
		}
#endif		
		inRetVal = inFLOW_RunFunction(pobTran, inOPTID[i]);

		/* 新補充UPT說明及新增退貨 [ _FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_ ]條件 2022/2/18 [SAM] */
#if (_MACHINE_TYPE_ == _CASTLE_TYPE_UPT1000_)
		/* 關閉刷卡與磁條的燈*/
		if (inOPTID[i] == _FUNCTION_GET_CARD_FIELDS_CTLS_)
		{
			inDISP_TrunOnOffLightOnPanel(Led, _LIGHT_OFF_);
		} else if (inOPTID[i] == _FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_)
		{
			inDISP_TrunOnOffLightOnPanel(Led2, _LIGHT_OFF_);
		}


#endif		
		if (inRetVal == VS_LAST_PAGE)
		{
			/* 選擇回上一頁 */
			i -= 2;
		} else if (inRetVal == VS_SUCCESS)
		{
			/* 成功，繼續下一步 */
		} else
		{
			break;
		}
	}

	return (inRetVal);
}
