
typedef enum {
	_FUNCTION_NULL_ = 0x00,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_,
	_FUNCTION_GET_CARD_FIELDS_FISC_,
	_FUNCTION_GET_CARD_FIELDS_FISC_CTLS_,
	_FUNCTION_GET_CARD_FIELDS_FISC_REDEND_CTLS_,
	_FUNCTION_GET_CARD_FIELDS_LOYALTY_REDEEM_, //10
	_FUNCTION_GET_CARD_FIELDS_LOYALTY_REDEEM_CTLS_,
	_FUNCTION_GET_BARCODE_,
	_FUNCTION_GET_CARD_FIELDS_HG_,
	_FUNCTION_GET_CREDIT_CARD_FIELDS_HG_,
	_FUNCTION_GET_CREDIT_CARD_FIELDS_MAIL_ORDER_,
	_FUNCTION_PRINT_RECEIPT_,
	_FUNCTION_PRINT_TOTAL_REPORT_,
	_FUNCTION_PRINT_DETAIL_REPORT_,
	_FUNCTION_PRINT_RECEIPT_BY_BUFFER_FLOW_,
	_FUNCTION_REPRINT_RECEIPT_BY_BUFFER_, //20
	_FUNCTION_PRINT_TOTAL_REPORT_BY_BUFFER_,
	_FUNCTION_PRINT_DETAIL_REPORT_BY_BUFFER_,
	_FUNCTION_REVIEW_,
	_FUNCTION_TOTAL_REVIEW_,
	_FUNCTION_DETAIL_REVIEW_,
	_FUNCTION_DETAIL_REVIEW_NEWUI_,
	_FUNCTION_GET_HOST_NUM_,
	_FUNCTION_GET_HOST_NUM_NEWUI_,
	_FUNCTION_USER_CHOICE_,
	_FUNCTION_CHECK_PAN_EXPDATE_, //30
	_FUNCTION_CHECK_PAN_EXPDATE_LOYALTY_REDEEM_,
	_FUNCTION_CHECK_BARCODE_LOYALTY_REDEEM_,
	_FUNCTION_CHECK_HG_PAN_EXPDATE_,
	_FUNCTION_UPDATE_INV_,
	_FUNCTION_UPDATE_BATCH_NUM_,
	_FUNCTION_DELETE_BATCH_,
	_FUNCTION_DELETE_BATCH_FLOW_,
	_FUNCTION_DELETE_ACCUM_,
	_FUNCTION_DELETE_ACCUM_FLOW_,
	_FUNCTION_CREATE_NEW_BATCH_TABLE_, //40
	_FUNCTION_REST_BATCH_INV_,
	_FUNCTION_GET_SIGNPAD_,
	_FUNCTION_All_HOST_MUST_SETTLE,
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_FUNCTION_DUPLICATE_CHECK_,
	_FUNCTION_DUPLICATE_SAVE_,
	_FUNCTION_IDLE_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_CHECK_TRANS_FUNCTION_FLOW_,
	_FUNCTION_VOID_CHECK_, //50
	_FUNCTION_VOID_CONFIRM_,
	_FUNCTION_DISPLAY_PLEASE_LOGON_FIRST_,
	_FUNCTION_MAKE_INSTALLMENT_DATA_,
	_FUNCTION_MAKE_REDEEM_DATA_,
	_FUNCTION_CUP_VOID_CHECK_,
	_FUNCTION_CUP_VOID_CONFIRM_,
	_FUNCTION_TIP_CHECK_,
	_FUNCTION_ADJUST_CHECK_,
	_FUNCTION_GET_CUP_PIN_,
	_FUNCTION_CUP_REFUND_LIMIT_CHECK_, //60
	_FUNCTION_GET_TRANSACTION_NO_FROM_PAN_,
	_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_SELECT_I_R_PAYMENT_TYPE_,

	_UPDATE_ACCUM_,
	_UPDATE_BATCH_,
	_COMM_MODEM_PREDIAL_,
	_POWER_SAVING_FLOW_SLEEP_,
	_POWER_SAVING_FLOW_STANDBY_,

	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_TIP_AMOUNT_, //70
	_CREDIT_FUNCTION_GET_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_DCC_TIP_AMOUNT_,
	_CREDIT_FUNCTION_GET_ADJUST_AMOUNT_,
	_CREDIT_FUNCTION_GET_STOREID_,
	_CREDIT_FUNCTION_GET_AUTHCODE_,
	_CREDIT_FUNCTION_GET_PERIOD_,
	_CREDIT_FUNCTION_GET_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_INSTFEE_,
	_CREDIT_FUNCTION_GET_PAY_AMOUNT_, //80
	_CREDIT_FUNCTION_GET_REDEEM_PAID_AMT_, /* 20190122 [SAM]  */
	_CREDIT_FUNCTION_GET_REDEEM_POINT_,
	_CREDIT_FUNCTION_PRINT_PARAM_TERM_,
	_CREDIT_FUNCTION_PRINT_PARAM_TERM_BY_BUFFER_,
	_CREDIT_FUNCTION_PRINT_DCC_PARAM_BY_BUFFER_,
	_CREDIT_FUNCTION_CHECKRESULT_,
	_CREDIT_FUNCTION_GET_ORI_TRANSDATE_,

	_CREDIT_FUNCTION_GET_ORI_AMOUNT_,
	_CREDIT_FUNCTION_GET_DCC_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_DCC_ORI_AMOUNT_, //90
	_CREDIT_FUNCTION_GET_ORI_PREAUTH_AMOUNT_,
	_CREDIT_FUNCTION_GET_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_PRODUCT_CODE_,
	_CREDIT_FUNCTION_CHECK_RESULT_SETTLE_,
	_CREDIT_FUNCTION_GET_CVV2_,
	_CREDIT_FUNCTION_GET_FISC_RRN_,
	_CREDIT_FUNCTION_GET_FISC_REFUND_,
	_CREDIT_FUNCTION_GET_FISC_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_RF_NUMBER_,

	_CREDIT_FUNCTION_GET_OPT_AMOUNT_, //100
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTFEE_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_CREDIT_FUNCTION_GET_OPT_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_, //110
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_ESVC_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_PREAUTH_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_FISC_RRN_,
	_CREDIT_FUNCTION_GET_OPT_FISC_REFUND_,
	_CREDIT_FUNCTION_GET_OPT_FISC_ORI_TRANSDATE_,

	_AMEX_FUNCTION_GET_4DBC_,
	_AMEX_FUNCTION_SET_TXN_ONLINE_OFFLINE_,
	_AMEX_FUNCTION_BUILD_AND_SEND_PACKET_, //120
	_AMEX_FUNCTION_VOID_CONFIRM_,
	_AMEX_FUNCTION_VOID_CHECK_,
	_AMEX_FUNCTION_TIP_CHECK_,
	_AMEX_FUNCTION_ADJUST_CHECK_,
	_AMEX_FUNCTION_MUST_SETTLE_CHECK_,

	_DINERS_FUNCTION_SET_TXN_ONLINE_OFFLINE_,
	_DINERS_FUNCTION_BUILD_AND_SEND_PACKET_,
	_DINERS_FUNCTION_VOID_CONFIRM_,
	_DINERS_FUNCTION_VOID_CHECK_,
	_DINERS_FUNCTION_TIP_CHECK_, //130
	_DINERS_FUNCTION_ADJUST_CHECK_,
	_DINERS_FUNCTION_MUST_SETTLE_CHECK_,
	_DINERS_FUNCTION_CHECK_TRANS_FUNCTION_,

	_EMV_PROCESS_,

	_FISC_CARD_PROCESS_TRAN_,
	_FISC_CARD_ENTER_PIN_,
	_FISC_CARD_VERIFY_PIN_,

	_DEBIT_SELECT_EF_,
	_DEBIT_READ_RECORDS_,
	_DEBIT_CREATE_CHECK_CODE_, //140
	_DEBIT_WRITE_RECORD_,

	_FUNC5_TMS_SELECT_FLOW_,
	_FUNC5_TASK_REPORT_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_DISCONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_FLOW_,
	_FUNCTION_TMS_SEND_RECEIVE_,
	_FUNCTION_TMS_SEND_RECEIVE_FTPS_,
	_FUNCTION_TMS_RESULT_HANDLE_,
	_FUN6_TMS_DOWNLOAD_,
	_FUN6_TRACELOG_UPLOAD_,
	_FUN6_TRACELOG_RESULT_,
	_FUNCTION_TMS_SCHEDULE_INQUIRE_,
	_FUNCTION_TMS_SCHEDULE_DOWNLOAD_,
	_FUNCTION_TMS_DOWNLOAD_SETTLE_,
	_FUNC5_DCC_DOWNLOAD_PARAMETER_,
	_FUNCTION_TMS_IDLE_UPDATE_,
	_FUNCTION_TMS_PRINT_RETURN_TASK_,
	_FUNCTION_TMS_REBOOT_,

	_CTLS_INIT_,

	_FUNCTION_ECR_RECEIVE_TRANSACTION_REQUEST_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_FOR_KIOSK_,
	_FUNCTION_ECR_SEND_INQUIRY_RESULT_,
	_FUNCTION_ECR_RECEIVE_SECOND_TRANSACTION_REQUEST_,
	_FUNCTION_ECR_LOAD_TMK_,
	_FUNCTION_ECR_CUSTOMER_FLOW_,
	_FUNCTION_ECR_CUSTOMER_FLOW2_,
	_FUNCTION_ECR_NO_TRT_RETURN_FLOW_, /* [國泰車麻吉] 新增二段式處理流程 2022/1/28 下午 3:58 [SAM] */
	/* MultiSlave */
	_MULTIFUNC_RC_COMMAND_,
	_MULTIFUNC_SEND_RESULT_,

	/* 票證DEMO */
	_TICKET_RUN_POLLING_CARD_,
	_TICKET_RUN_DEDUCT_,
	_TICKET_RUN_CHECK_BALANCE_,
	_TICKET_RUN_TOP_UP_,
	_TICKET_CHECK_AMOUNT_,
	_TICKET_FUNC_IPASS_REGISTER_,
	_TICKET_LOGON_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_TICKET_CHECK_TRANS_ENABLE_,
	_TICKET_GET_PARM_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_FUNCTION_SET_TXN_ONLINE_OFFLINE_,
	_TICKET_FUNCTION_BUILD_AND_SEND_PACKET_,
	_TICKET_CHECK_ACK_HOST_,
	_TICKET_CONNECT_,
	_TICKET_DISCONNECT_,
	_TICKET_GET_CARD_,
	_TICKET_CASTLE_POLLING_,
	_TICKET_GET_DAVTI_PARM_,
	_TICKET_UPDATE_ACCUM_,
	_TICKET_UPDATE_BATCH_,
	_TICKET_UPDATE_INV_,
	_TICKET_IPASS_TAPCARD_FIRST_,
	_TICKET_IPASS_TAPCARD_SECOND_,
	_TICKET_IPASS_QUERYING_FLOW_,
	_TICKET_ECC_API_FLOW_,
	_TICKET_ECC_SETTLE_FLOW_,
	_TICKET_GET_VOID_TOP_UP_AMOUNT_FROM_BATCH_,

	_EDC_BOOTING_DISPLAY_INITIAL_, /* 顯示函式庫初始化 */
	_EDC_BOOTING_PRINT_INITIAL_,
	_EDC_BOOTING_PRINT_IMAGE_INITIAL_,
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_,
	_EDC_BOOTING_LOAD_TABLE_,
	_EDC_BOOTING_SYNC_DEBUG_,
	_EDC_BOOTING_COMM_INITIAL_,
	_EDC_BOOTING_ECR_INITIAL_,
	_EDC_BOOTING_MULTI_FIRST_INITIAL_,
	_EDC_BOOTING_EMV_INITIAL_,
	_EDC_BOOTING_TMSOK_CHECK_INITIAL_,
	_EDC_BOOTING_ETICKET_INITIAL_,
	_EDC_BOOTING_CTLS_INITIAL_,
	_EDC_BOOTING_SQLITE_INITIAL_,
	_EDC_BOOTING_CUP_LOGON_,
	_EDC_BOOTING_TSAM_INITIAL_,
	_EDC_BOOTING_TMS_INQUIRE_,
	_EDC_BOOTING_TMS_DCC_SCHEDULE_,
	_EDC_BOOTING_POWER_ON_PASSWORD_,
	_EDC_BOOTING_CLEAR_AP_DUMP_,
	_EDC_BOOTING_PROCESS_CRADLE_,
	_EDC_BOOTING_POWER_MANAGEMENT_,
	_EDC_BOOTING_REPRINT_POWEROFF_,
	_EDC_BOOTING_UPDATE_PARAMETER_POWER_ON_,
	_EDC_BOOTING_UPDATE_SUCCESS_REPORT_,
	_EDC_BOOTING_TMS_DOWNLOAD_,
	_EDC_BOOTING_CHECK_BATCH_AMT_DATA_, /* 富邦新增開機時檢查總額問題 2020/5/13 上午 10:25 [SAM] */
	_EDC_BOOTING_ETICKET_INITIAL_FISC, /* [新增電票悠遊卡功能]  新增票證初始化功能 [SAM] 2022/6/8 下午 5:52 */

	_FUBON_FUNCTION_MUST_SETTLE_CHECK_,
	_FUBON_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_FUBON_SET_ONLINE_OFFLINE_,
	_FUBON_FUNCTION_MAKE_REFNO_,
	_FUBON_TURN_OFF_SETTLE_FLAG_,


	_COMM_START_,
	_COMM_END_,
	_NEXSYS_ESC_UPLOAD_,
	_NEXSYS_ESC_UPLOAD_IDLE_,
	_NEXSYS_ESC_UPLOAD_SETTLE_,
	_NEXSYS_ESC_UPDATE_RE_PRINT_,
	_NEXSYS_ESC_CHECK_,

	_FUNCTION_NEXSYS_TMS_SELECT_FLOW_, /*  20190131 TMS [SAM] */
	_FUNCTION_NEXSYS_TMS_CONNECT_, /*  20190131 TMS [SAM] */
	_FUNCTION_NEXSYS_TMS_SEND_RECEIVE_FLOW_, /*  20190131 TMS [SAM] */
	_FUNCTION_NEXSYS_TMS_RESULT_HANDLE_, /*  20190131 TMS [SAM] */
	_FUNCTION_NEXSYS_MANUAL_TMS_RESULT_HANDLE_, /*  20190131 TMS [SAM] */
	_FUNCTION_NEXSYS_RENEW_FPT_TIME_, /*  2019/12/10 下午 4:11 TMS [SAM] */

	_CREDIT_FUNCTION_SET_SETTLE_FLAG_ON_,
	_FUNCTION_SET_TID_MID_,
	_FUNCTION_GET_ORIG_TRANSDATE_,

	/* [新增電票悠遊卡功能] 新增功能 ID [SAM] 2022/6/8 下午 5:52 */
	_FUNCTION_CHECK_TERM_STATUS_CMAS_,
	_CMAS_DECIDE_TRANS_TYPE_,
	_CMAS_API_FLOW_,
	_CMAS_UPDATE_INV_,
	_CMAS_UPDATE_BATCH_,
	_CMAS_GET_PARM_,
	_FUNCTION_USER_CHOICE_CMAS_,
	_CMAS_SETTLE_FLOW_,
	_CMAS_SET_UPDATE_BATCH_FLAG_,
	_CMAS_UPDATE_ACCUM_,
	_CMAS_CHECK_TRANS_ENABLE_,

	/* [新增電票悠遊卡功能] 加入悠遊卡功能時，在 TRT FLOW裏使用 [SAM] 2022/6/8 下午 5:52 */
	_FUNCTION_CHECK_TIME_, /* 新增確認系統日期與版本日期 */
	/* [新增SVC功能]  [SAM]  START */
	_SVC_TMS_DOWNLOAD_,
	_SVC_AUTO_LOAD_,
	_FUNCTION_GET_SVC_CARD_FIELDS_CTLS_,
	_SVC_UPDATE_ACCUM_,
	_SVC_ISO_FUNCTION_BUILD_AND_SEND_PACKET_,
	_SVC_DISPLAY_POINT_,
	_SVC_COMPARE_POINT_,
	/* [新增SVC功能]  [SAM]  END */
                
        /* 20230201 Miyano Costco 相關功能 Start */
        _COSTCO_SCANPAY_,
        /* 20230201 Miyano Costco 相關功能 End */
                
} FUNCTION;

typedef struct {
	int inFuncId;
	FUNC_POINT inFunctionPoint;
} FUNC_TABLE;


extern FUNC_TABLE FunctionTable[];

int inFUNC_TABLE_Test(void);
